import importlib.util
import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAINNET_ADDRESS = "0x3197c42f4a06f7be32a9a742ac2a766f0ff682c6"
RESERVE_WALLET = "0x5e8F84748612B913aAcC937492AC25dc5630E246"
RESERVE_TX = "0x4c342e1f4c969d0a73018637b778d5a76bd05f54749ff1fd2d19327fd5c01c67"
SECOND_RESERVE_TX = "0xfffb674448abdbd3af45bb0a30c48e5fbb0e675542b971f031381254b5dc5317"
TELEGRAM_URL = "https://t.me/gcagochinaofficial"
SWAP_TEST_BUY_TX = "0xf79e52ea56a299a30c2d297be99c970295864ed262c01fdcb7e3f60ca669b040"
SWAP_TEST_SELL_TX = "0x0ff618062abc6e28933699d4e3bd723026f8505e4a0155db3068073b6fdc86e7"
OFFICIAL_POOL_ADDRESS = "0xfe6a598bf738d7eec9640897064ca3a490128d3d447ced96077aef8e9dd1c1d0"
BASE_USDT_ADDRESS = "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
OFFICIAL_DEXSCREENER_URL = f"https://dexscreener.com/base/{OFFICIAL_POOL_ADDRESS}"
OFFICIAL_GECKOTERMINAL_URL = f"https://www.geckoterminal.com/base/pools/{OFFICIAL_POOL_ADDRESS}"
OFFICIAL_UNISWAP_POOL_URL = f"https://app.uniswap.org/explore/pools/base/{OFFICIAL_POOL_ADDRESS}"
OFFICIAL_SWAP_URL = (
    f"https://app.uniswap.org/swap?chain=base&inputCurrency={BASE_USDT_ADDRESS}"
    f"&outputCurrency={MAINNET_ADDRESS}"
)
OFFICIAL_SWAP_URL_HTML = OFFICIAL_SWAP_URL.replace("&", "&amp;")
MARKET_PAGE_URL = "https://gcagochina.com/markets.html"
VERIFY_PAGE_URL = "https://gcagochina.com/verify.html"
SUPPLY_PAGE_URL = "https://gcagochina.com/supply.html"
SECURITY_PAGE_URL = "https://gcagochina.com/security.html"
RISK_PAGE_URL = "https://gcagochina.com/risk.html"
FAQ_URL = "https://gcagochina.com/faq.html"
OLD_WETH_POOL_ADDRESS = "0x79fc0b367adbd79118c664f5ee27eb6ff8cb69ff"
WELL_KNOWN_TOKEN_URL = "https://gcagochina.com/.well-known/gca-token.json"
SECURITY_CONTACT_URL = "https://gcagochina.com/.well-known/security.txt"
MEMBER_PROGRAM_URL = "https://gcagochina.com/member-program.json"


class LaunchPackageTests(unittest.TestCase):
    def test_public_site_health_check_script_matches_canonical_identity(self):
        script_path = ROOT / "tools" / "check_public_site.py"
        script = script_path.read_text()
        spec = importlib.util.spec_from_file_location("check_public_site", script_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        self.assertIn("DEFAULT_BASE_URL = \"https://gcagochina.com/\"", script)
        self.assertIn(MAINNET_ADDRESS, script)
        self.assertIn(OFFICIAL_POOL_ADDRESS, script)
        self.assertIn(BASE_USDT_ADDRESS, script)
        self.assertIn(OLD_WETH_POOL_ADDRESS, script)
        self.assertIn("/.well-known/gca-token.json", script)
        self.assertIn("/.well-known/security.txt", script)
        self.assertIn("[ok]", script)
        self.assertIn("[fail]", script)

        module.validate_root((ROOT / "site" / "index.html").read_text())
        module.validate_verify((ROOT / "site" / "verify.html").read_text())
        module.validate_markets((ROOT / "site" / "markets.html").read_text())
        module.validate_project_json((ROOT / "site" / "project.json").read_text())
        module.validate_tokenlist_json((ROOT / "site" / "tokenlist.json").read_text())
        module.validate_well_known_json((ROOT / "site" / ".well-known" / "gca-token.json").read_text())
        module.validate_security_txt((ROOT / "site" / ".well-known" / "security.txt").read_text())
        module.validate_sitemap((ROOT / "site" / "sitemap.xml").read_text())
        module.validate_robots((ROOT / "site" / "robots.txt").read_text())

        with self.assertRaises(module.SiteCheckError):
            module.validate_root(f"GCA/WETH {OLD_WETH_POOL_ADDRESS}")

    def test_pages_publish_workflow_syncs_site_to_gh_pages(self):
        workflow = (ROOT / ".github" / "workflows" / "publish-site.yml").read_text()

        self.assertIn("name: Publish GCA Site", workflow)
        self.assertIn("branches:", workflow)
        self.assertIn("- main", workflow)
        self.assertIn('"site/**"', workflow)
        self.assertIn('".github/workflows/publish-site.yml"', workflow)
        self.assertIn("workflow_dispatch:", workflow)
        self.assertIn("contents: write", workflow)
        self.assertIn("concurrency:", workflow)
        self.assertIn("actions/checkout@v4", workflow)
        self.assertIn("fetch-depth: 0", workflow)
        self.assertIn("timeout-minutes: 20", workflow)
        self.assertIn("actions/setup-python@v5", workflow)
        self.assertIn('python-version: "3.12"', workflow)
        self.assertIn("python -m pip install -r requirements-token-dev.txt", workflow)
        self.assertIn("Run full validation suite", workflow)
        self.assertIn("python -m unittest -v", workflow)
        self.assertIn("git fetch origin gh-pages", workflow)
        self.assertIn("git worktree add ../gh-pages origin/gh-pages", workflow)
        self.assertIn("rsync -a --delete --exclude .git site/ ../gh-pages/", workflow)
        self.assertIn("git add -A", workflow)
        self.assertIn("No website changes to publish.", workflow)
        self.assertIn('git commit -m "Publish site from ${GITHUB_SHA::7} [skip ci]"', workflow)
        self.assertIn("git push origin HEAD:gh-pages", workflow)
        self.assertNotIn("secrets.", workflow)
        self.assertNotIn("PRIVATE", workflow)
        self.assertNotIn("mnemonic", workflow.lower())

    def test_public_site_health_check_workflow_runs_live_script(self):
        workflow_path = ROOT / ".github" / "workflows" / "check-public-site.yml"
        workflow = workflow_path.read_text()

        self.assertIn("name: Check GCA Public Site", workflow)
        self.assertIn("workflow_dispatch:", workflow)
        self.assertIn("schedule:", workflow)
        self.assertIn('cron: "17 3 * * *"', workflow)
        self.assertIn("branches:", workflow)
        self.assertIn("- main", workflow)
        self.assertIn('"tools/check_public_site.py"', workflow)
        self.assertIn('".github/workflows/check-public-site.yml"', workflow)
        self.assertIn("contents: read", workflow)
        self.assertIn("concurrency:", workflow)
        self.assertIn("timeout-minutes: 10", workflow)
        self.assertIn("actions/checkout@v4", workflow)
        self.assertIn("actions/setup-python@v5", workflow)
        self.assertIn('python-version: "3.12"', workflow)
        self.assertIn("python -m pip install certifi", workflow)
        self.assertIn("python tools/check_public_site.py --timeout 30", workflow)
        self.assertNotIn("contents: write", workflow)
        self.assertNotIn("secrets.", workflow)
        self.assertNotIn("PRIVATE", workflow)
        self.assertNotIn("mnemonic", workflow.lower())

    def test_logo_matches_basescan_size_target(self):
        logo = (ROOT / "brand" / "gca-logo.svg").read_text()
        self.assertIn('width="32"', logo)
        self.assertIn('height="32"', logo)
        self.assertIn("GCA token logo", logo)
        self.assertTrue((ROOT / "brand" / "gca-logo.png").exists())
        self.assertTrue((ROOT / "site" / "assets" / "gca-logo.png").exists())

    def test_public_site_uses_mainnet_identity(self):
        site = (ROOT / "site" / "index.html").read_text()
        buy = (ROOT / "site" / "buy.html").read_text()
        markets = (ROOT / "site" / "markets.html").read_text()
        supply = (ROOT / "site" / "supply.html").read_text()
        security = (ROOT / "site" / "security.html").read_text()
        risk = (ROOT / "site" / "risk.html").read_text()
        faq = (ROOT / "site" / "faq.html").read_text()
        status = (ROOT / "site" / "status.html").read_text()
        listing = (ROOT / "site" / "listing-kit.html").read_text()
        verify = (ROOT / "site" / "verify.html").read_text()
        project = json.loads((ROOT / "site" / "project.json").read_text())
        utility = (ROOT / "site" / "utility.html").read_text()
        members = (ROOT / "site" / "members.html").read_text()
        self.assertIn("Base Mainnet", site)
        self.assertIn("chainId 8453", site)
        self.assertIn(MAINNET_ADDRESS, site)
        self.assertIn(MAINNET_ADDRESS, buy)
        self.assertIn(MAINNET_ADDRESS, markets)
        self.assertIn(MAINNET_ADDRESS, supply)
        self.assertIn(MAINNET_ADDRESS, security)
        self.assertIn(MAINNET_ADDRESS, risk)
        self.assertIn(MAINNET_ADDRESS, faq)
        self.assertIn(MAINNET_ADDRESS, status)
        self.assertIn(MAINNET_ADDRESS, listing)
        self.assertIn(MAINNET_ADDRESS, verify)
        self.assertEqual(project["contractAddress"], MAINNET_ADDRESS)
        self.assertIn(MAINNET_ADDRESS, utility)
        self.assertIn(MAINNET_ADDRESS, members)
        self.assertIn("Base Mainnet", members)
        self.assertIn("Base Mainnet", buy)
        self.assertIn("chainId 8453", buy)
        self.assertIn("https://basescan.org/address/", site)
        self.assertNotIn("sepolia.basescan.org", site)
        self.assertNotIn("sepolia.basescan.org", buy)
        self.assertNotIn("sepolia.basescan.org", markets)
        self.assertNotIn("sepolia.basescan.org", supply)
        self.assertNotIn("sepolia.basescan.org", security)
        self.assertNotIn("sepolia.basescan.org", risk)
        self.assertNotIn("sepolia.basescan.org", faq)
        self.assertNotIn("sepolia.basescan.org", status)
        self.assertNotIn("sepolia.basescan.org", listing)
        self.assertNotIn("sepolia.basescan.org", verify)

    def test_public_site_sets_custom_domain(self):
        cname = (ROOT / "site" / "CNAME").read_text().strip()
        self.assertEqual(cname, "gcagochina.com")

    def test_site_has_discovery_files(self):
        robots = (ROOT / "site" / "robots.txt").read_text()
        sitemap = (ROOT / "site" / "sitemap.xml").read_text()

        self.assertTrue((ROOT / "site" / ".nojekyll").exists())
        self.assertIn("User-agent: *", robots)
        self.assertIn("Allow: /", robots)
        self.assertIn("Allow: /member-program.json", robots)
        self.assertIn("Allow: /.well-known/gca-token.json", robots)
        self.assertIn("Allow: /.well-known/security.txt", robots)
        self.assertIn("Sitemap: https://gcagochina.com/sitemap.xml", robots)
        self.assertIn("https://gcagochina.com/", sitemap)
        self.assertIn(VERIFY_PAGE_URL, sitemap)
        self.assertIn("https://gcagochina.com/status.html", sitemap)
        self.assertIn("https://gcagochina.com/listing-kit.html", sitemap)
        self.assertIn("https://gcagochina.com/project.json", sitemap)
        self.assertIn("https://gcagochina.com/tokenlist.json", sitemap)
        self.assertIn("https://gcagochina.com/buy.html", sitemap)
        self.assertIn("https://gcagochina.com/markets.html", sitemap)
        self.assertIn("https://gcagochina.com/supply.html", sitemap)
        self.assertIn("https://gcagochina.com/security.html", sitemap)
        self.assertIn("https://gcagochina.com/risk.html", sitemap)
        self.assertIn("https://gcagochina.com/faq.html", sitemap)
        self.assertIn(MEMBER_PROGRAM_URL, sitemap)
        self.assertIn("https://gcagochina.com/whitepaper.html", sitemap)
        self.assertIn(WELL_KNOWN_TOKEN_URL, sitemap)
        self.assertIn(SECURITY_CONTACT_URL, sitemap)

    def test_well_known_identity_files_are_public_and_conservative(self):
        identity = json.loads((ROOT / "site" / ".well-known" / "gca-token.json").read_text())
        security = (ROOT / "site" / ".well-known" / "security.txt").read_text()

        self.assertEqual(identity["schema"], WELL_KNOWN_TOKEN_URL)
        self.assertEqual(identity["lastUpdated"], "2026-05-12")
        self.assertEqual(identity["network"]["name"], "Base Mainnet")
        self.assertEqual(identity["network"]["chainId"], 8453)
        self.assertEqual(identity["token"]["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(identity["token"]["decimals"], 18)
        self.assertEqual(identity["token"]["totalSupply"], "1000000000")
        self.assertFalse(identity["token"]["mintingSupportedAfterDeployment"])
        self.assertFalse(identity["token"]["taxes"])
        self.assertFalse(identity["token"]["blacklist"])
        self.assertFalse(identity["token"]["adminControls"])
        self.assertEqual(identity["officialUrls"]["verify"], VERIFY_PAGE_URL)
        self.assertEqual(identity["officialUrls"]["wellKnownTokenIdentity"], WELL_KNOWN_TOKEN_URL)
        self.assertEqual(identity["officialUrls"]["securityContact"], SECURITY_CONTACT_URL)
        self.assertEqual(identity["officialUrls"]["memberProgramRules"], MEMBER_PROGRAM_URL)
        self.assertEqual(identity["officialUrls"]["telegram"], TELEGRAM_URL)
        self.assertEqual(identity["market"]["officialPair"], "GCA/USDT")
        self.assertEqual(identity["market"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(identity["market"]["quoteAssetAddress"], BASE_USDT_ADDRESS)
        self.assertEqual(identity["market"]["geckoTerminal"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(identity["market"]["dexScreener"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(identity["market"]["officialSwap"], OFFICIAL_SWAP_URL)
        self.assertEqual(identity["supplyDisclosure"]["ownerReserveWallet"], RESERVE_WALLET)
        self.assertEqual(identity["supplyDisclosure"]["ownerReserveTransferTxs"], [RESERVE_TX, SECOND_RESERVE_TX])
        self.assertEqual(identity["platformStatus"]["baseScanTokenProfile"], "submitted-awaiting-review")
        self.assertEqual(identity["platformStatus"]["geckoTerminalTokenInfo"], "approved-2026-05-11")
        self.assertEqual(identity["platformStatus"]["thirdPartyAudit"], "not-completed")
        self.assertTrue(identity["securityFacts"]["sourceVerifiedOnBaseScan"])
        self.assertTrue(identity["securityFacts"]["fixedSupply"])
        self.assertFalse(identity["securityFacts"]["postDeploymentMintFunction"])
        self.assertFalse(identity["securityFacts"]["ownerOrAdminRole"])
        self.assertFalse(identity["securityFacts"]["thirdPartyAuditCompleted"])
        self.assertIn("No third-party audit has been completed.", identity["publicClaimBoundaries"]["safeClaims"])
        self.assertIn("deep liquidity, price backing, or return promises", identity["publicClaimBoundaries"]["doNotClaim"])
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, json.dumps(identity))

        self.assertIn("Contact: mailto:GCAgochina@outlook.com", security)
        self.assertIn(f"Canonical: {SECURITY_CONTACT_URL}", security)
        self.assertIn("Policy: https://gcagochina.com/security.html", security)
        self.assertIn("Preferred-Languages: en, zh", security)
        self.assertIn("Expires: 2027-05-12T00:00:00+07:00", security)

    def test_public_site_discloses_current_operational_status(self):
        site = (ROOT / "site" / "index.html").read_text()
        self.assertIn("BaseScan token profile update has been submitted", site)
        self.assertIn('href="verify.html"', site)
        self.assertIn('href="buy.html"', site)
        self.assertIn('href="markets.html"', site)
        self.assertIn('href="supply.html"', site)
        self.assertIn('href="security.html"', site)
        self.assertIn('href="risk.html"', site)
        self.assertIn('href="faq.html"', site)
        self.assertIn('href="status.html"', site)
        self.assertIn('href="listing-kit.html"', site)
        self.assertIn("Go China Access", site)
        self.assertIn("Go China AI Quant Access", site)
        self.assertIn("Go China macro narrative", site)
        self.assertIn("Web3 Radar-style quant research", site)
        self.assertIn("planned access path for liquidation replay, backtesting, risk alerts, ENTRY_READY review, and position sizing", site)
        self.assertIn("local verified-access backend", site)
        self.assertIn("Verified Utility: Web3 Radar Access Layer", site)
        self.assertIn("Access Bridge Pipeline", site)
        self.assertIn("Users submit email, Telegram, Base wallet, declared GCA balance, and program intent", site)
        self.assertIn("verified balances create service-access ledger records only", site)
        self.assertIn("each registered user may verify one wallet holding at least 10,000 GCA", site)
        self.assertIn("one-time 100 Web3 Radar utility credits ledger record", site)
        self.assertIn("one wallet holding at least 1,000,000 GCA", site)
        self.assertIn("GCA Member status", site)
        self.assertIn("not cash, tokens, income, reimbursement, or trading permission", site)
        self.assertIn("400,000,000 GCA / 40%", site)
        self.assertIn("600,000,000 GCA / 60%", site)
        self.assertIn("exact circulating supply should still be verified", site)
        self.assertIn(RESERVE_WALLET, site)
        self.assertIn(RESERVE_TX, site)
        self.assertIn(SECOND_RESERVE_TX, site)
        self.assertIn("mailto:GCAgochina@outlook.com", site)
        self.assertIn(TELEGRAM_URL, site)
        self.assertIn("Project contact email", site)
        self.assertNotIn("https://x.com/GCAgochina", site)
        self.assertNotIn("Official X profile", site)
        self.assertIn("No third-party audit has been completed", site)
        self.assertIn("Security &amp; Transparency", site)
        self.assertIn("Third-party audit quote requests were submitted to QuillAudits, Hacken, and OpenZeppelin on 2026-05-10", site)
        self.assertIn("then deferred by owner decision", site)
        self.assertIn("no post-deployment mint function", site)
        self.assertIn("no owner/admin role", site)
        self.assertIn("no owner/admin role, proxy or upgrade path, pause switch, blacklist, transfer tax, hidden fee, custody, or withdrawal path", site)
        self.assertIn("pool is shallow", site)
        self.assertIn("high price impact and slippage", site)
        self.assertIn(OFFICIAL_POOL_ADDRESS, site)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, site)
        self.assertIn("Market References", site)
        self.assertIn("GCA/USDT", site)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, site)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, site)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, site)
        self.assertIn("GeckoTerminal token information was approved on 2026-05-11", site)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, site)
        self.assertIn("starter liquidity only", site)

    def test_members_page_supports_local_pre_registration_safely(self):
        members = (ROOT / "site" / "members.html").read_text()
        self.assertIn("GCA Member Pre-Registration", members)
        self.assertIn("This page creates a local pre-registration packet", members)
        self.assertIn("does not create a live Web3 Radar account", members)
        self.assertIn("10,000 GCA", members)
        self.assertIn("100 Web3 Radar utility credits", members)
        self.assertIn("1,000,000 GCA", members)
        self.assertIn("GCA Member", members)
        self.assertIn("Connect Wallet", members)
        self.assertIn("Generate Packet", members)
        self.assertIn("Submit Packet", members)
        self.assertIn("Copy Packet", members)
        self.assertIn("Download JSON", members)
        self.assertIn("Email Packet", members)
        self.assertIn('const SUBMISSION_ENDPOINT = "";', members)
        self.assertIn('const REVIEWED_WEB3_RADAR_ENDPOINT_PATH = "/gca/pre-registrations";', members)
        self.assertIn('const WALLET_VERIFICATION_ENDPOINT_PATH = "/gca/wallet-verifications";', members)
        self.assertIn('const CREDIT_LEDGER_ENDPOINT_PATH = "/gca/credit-ledger";', members)
        self.assertIn('const MEMBER_LEDGER_ENDPOINT_PATH = "/gca/member-ledger";', members)
        self.assertIn("fetch(SUBMISSION_ENDPOINT", members)
        self.assertIn("Direct submission is not connected", members)
        self.assertIn("/gca/wallet-verifications", members)
        self.assertIn("/gca/credit-ledger", members)
        self.assertIn("/gca/member-ledger", members)
        self.assertIn("/gca/member-review", members)
        self.assertIn("Current public submission mode", members)
        self.assertIn("local-only-pre-registration-backend-verification-ready-public-claim-not-connected", members)
        self.assertIn("No private key, seed phrase, exchange API secret, withdrawal permission, or custody request", members)
        self.assertIn("No cash, token rebate, income, reimbursement, trading permission, or risk-control bypass", members)
        self.assertIn("walletAddressFormatOk", members)
        self.assertIn("eth_requestAccounts", members)
        self.assertIn("GCAgochina@outlook.com", members)
        self.assertIn("180 days", members)
        self.assertIn("30 days", members)
        self.assertIn("5-10 business days", members)
        self.assertIn("member-program.json", members)
        self.assertIn("CREDIT_EXPIRY_DAYS = 180", members)
        self.assertIn("MEMBER_REFRESH_DAYS = 30", members)
        self.assertIn("reviewStatuses", members)
        self.assertIn("ledger_recorded", members)

    def test_member_program_json_sets_safe_rules(self):
        rules = json.loads((ROOT / "site" / "member-program.json").read_text())

        self.assertEqual(rules["schema"], MEMBER_PROGRAM_URL)
        self.assertEqual(rules["status"], "rules-published-public-claim-not-connected")
        self.assertEqual(rules["chainId"], 8453)
        self.assertEqual(rules["token"]["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(rules["holderBonus"]["minimumHolding"], "10000 GCA")
        self.assertEqual(rules["holderBonus"]["creditAmount"], "100 Web3 Radar utility credits")
        self.assertEqual(rules["holderBonus"]["creditExpiry"], "180 days after ledger activation unless a later published policy extends it")
        self.assertIn("ENTRY_READY signal review", rules["holderBonus"]["spendScope"])
        self.assertIn("not transferable", " ".join(rules["holderBonus"]["spendRules"]))
        self.assertEqual(rules["memberTier"]["minimumHolding"], "1000000 GCA")
        self.assertEqual(rules["memberTier"]["refreshCadence"], "30 days after activation, or earlier if the user requests a manual recheck")
        self.assertIn("priority support", rules["memberTier"]["accessScope"])
        self.assertIn("risk-control bypass", " ".join(rules["memberTier"]["accessRules"]))
        self.assertFalse(rules["verification"]["directSubmissionEndpointConfigured"])
        self.assertEqual(rules["supportWorkflow"]["contactEmail"], "GCAgochina@outlook.com")
        self.assertIn("not a guarantee", rules["supportWorkflow"]["targetFirstResponse"])
        self.assertIn("ledger_recorded", rules["supportWorkflow"]["reviewStatuses"])
        self.assertIn("public self-service claiming is not connected", " ".join(rules["publicClaimBoundaries"]["safeClaims"]))
        self.assertIn("credits or membership are cash", " ".join(rules["publicClaimBoundaries"]["doNotClaim"]))
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, json.dumps(rules))

    def test_utility_page_connects_gca_to_quant_tools_safely(self):
        utility = (ROOT / "site" / "utility.html").read_text()
        self.assertIn("GCA Utility Thesis", utility)
        self.assertIn("Go China macro-narrative token", utility)
        self.assertIn("Web3 Radar-style non-custodial quant tools", utility)
        self.assertIn("liquidation replay reports", utility)
        self.assertIn("risk-warning credits", utility)
        self.assertIn("realistic backtests", utility)
        self.assertIn("ENTRY_READY signal review", utility)
        self.assertIn("Position calculator", utility)
        self.assertIn("risk-control training", utility)
        self.assertIn("GCA Member status", utility)
        self.assertIn("Verified Holder Programs", utility)
        self.assertIn("one wallet holding at least 10,000 GCA", utility)
        self.assertIn("one-time 100 Web3 Radar utility credits ledger record", utility)
        self.assertIn("one wallet holding at least 1,000,000 GCA", utility)
        self.assertIn("higher utility credit limits", utility)
        self.assertIn("not token rebates", utility)
        self.assertIn("Platform revenue distribution", utility)
        self.assertIn("Token ownership bypassing risk controls", utility)
        self.assertIn("verified utility backend path", utility)
        self.assertIn("does not represent custody, redemption rights", utility)
        self.assertIn("return guarantees", utility)

    def test_verify_page_centralizes_official_identity_and_status(self):
        verify = (ROOT / "site" / "verify.html").read_text()

        self.assertIn("Verify GCA", verify)
        self.assertIn("Official Links", verify)
        self.assertIn("Canonical Token Identity", verify)
        self.assertIn("Official Market Identity", verify)
        self.assertIn("Current Review Status", verify)
        self.assertIn("Base Mainnet / 8453", verify)
        self.assertIn("Chain ID", verify)
        self.assertIn("8453", verify)
        self.assertIn(MAINNET_ADDRESS, verify)
        self.assertIn(BASE_USDT_ADDRESS, verify)
        self.assertIn(OFFICIAL_POOL_ADDRESS, verify)
        self.assertIn("GCA/USDT", verify)
        self.assertIn("Uniswap v4", verify)
        self.assertIn("0.01%", verify)
        self.assertIn(TELEGRAM_URL, verify)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, verify)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, verify)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, verify)
        self.assertIn("BaseScan source code", verify)
        self.assertIn("Verified", verify)
        self.assertIn("BaseScan token profile", verify)
        self.assertIn("Submitted, awaiting review", verify)
        self.assertIn("Approved 2026-05-11", verify)
        self.assertIn("Submitted 2026-05-10; removal not confirmed", verify)
        self.assertIn("Third-party audit", verify)
        self.assertIn("Not completed", verify)
        self.assertIn("Starter-depth only; high slippage possible", verify)
        self.assertIn("Do not describe GCA as externally audited", verify)
        self.assertIn("Avoid Unverified Links", verify)
        self.assertIn("Do not use any claimed official X profile", verify)
        self.assertIn("Do not use artificial volume", verify)
        self.assertIn("private keys, seed phrases, exchange API secrets", verify)
        self.assertIn('href="project.json"', verify)
        self.assertIn('href="tokenlist.json"', verify)
        self.assertIn('href=".well-known/gca-token.json"', verify)
        self.assertIn("well-known token identity", verify)
        self.assertIn('href="status.html"', verify)
        self.assertIn('href="listing-kit.html"', verify)
        self.assertIn("copyContract", verify)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, verify)

    def test_buy_page_is_official_and_conservative(self):
        buy = (ROOT / "site" / "buy.html").read_text()
        self.assertIn("Buy GCA", buy)
        self.assertIn("Open Uniswap Swap", buy)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, buy)
        self.assertIn(MAINNET_ADDRESS, buy)
        self.assertIn(BASE_USDT_ADDRESS, buy)
        self.assertIn("Base Mainnet", buy)
        self.assertIn("Chain ID", buy)
        self.assertIn("8453", buy)
        self.assertIn("MetaMask Import", buy)
        self.assertIn("Add to MetaMask", buy)
        self.assertIn("GeckoTerminal pool", buy)
        self.assertIn("GCA/USDT", buy)
        self.assertIn("GCA/USDT approved", buy)
        self.assertIn(OFFICIAL_POOL_ADDRESS, buy)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, buy)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, buy)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, buy)
        self.assertIn("A Blockaid / MetaMask false-positive report was submitted on 2026-05-10", buy)
        self.assertIn("does not mean wallet warnings have been removed", buy)
        self.assertIn("no third-party audit has been completed", buy)
        self.assertIn("This is not investment advice", buy)
        self.assertIn("does not guarantee price, liquidity, execution, or safety", buy)
        self.assertIn("If a wallet or DEX warning appears, stop and verify", buy)

    def test_markets_page_is_canonical_and_conservative(self):
        markets = (ROOT / "site" / "markets.html").read_text()

        self.assertIn("Official GCA Markets", markets)
        self.assertIn("canonical market page", markets)
        self.assertIn("Base Mainnet / 8453", markets)
        self.assertIn("GCA/USDT", markets)
        self.assertIn("Uniswap v4 / 0.01%", markets)
        self.assertIn("Approved 2026-05-11", markets)
        self.assertIn(MAINNET_ADDRESS, markets)
        self.assertIn(OFFICIAL_POOL_ADDRESS, markets)
        self.assertIn(BASE_USDT_ADDRESS, markets)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, markets)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, markets)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, markets)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, markets)
        self.assertIn("Earlier pilot liquidity may exist historically", markets)
        self.assertIn("starter-depth liquidity only", markets)
        self.assertIn("not proof of organic demand", markets)
        self.assertIn("Do not use artificial volume", markets)
        self.assertIn("BaseScan token profile", markets)
        self.assertIn("Awaiting review", markets)
        self.assertIn("Third-party audit", markets)
        self.assertIn("Not completed", markets)
        self.assertIn('href="buy.html"', markets)
        self.assertIn('href="status.html"', markets)
        self.assertIn('href="listing-kit.html"', markets)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, markets)

    def test_supply_page_explains_total_supply_and_reserve(self):
        supply = (ROOT / "site" / "supply.html").read_text()

        self.assertIn("GCA Supply and Reserve", supply)
        self.assertIn("smart contract total supply is fixed at 1,000,000,000 GCA", supply)
        self.assertIn("400,000,000 GCA / 40%", supply)
        self.assertIn("600,000,000 GCA / 60%", supply)
        self.assertIn("No post-deploy mint", supply)
        self.assertIn("Why Explorers Show 1B", supply)
        self.assertIn("totalSupply", supply)
        self.assertIn("Moving tokens between wallets or into liquidity does not reduce totalSupply", supply)
        self.assertIn("What 40/60 Means", supply)
        self.assertIn("public allocation target", supply)
        self.assertIn(RESERVE_WALLET, supply)
        self.assertIn(RESERVE_TX, supply)
        self.assertIn(SECOND_RESERVE_TX, supply)
        self.assertIn("Owner wallet, not locked", supply)
        self.assertIn("Data Platforms", supply)
        self.assertIn("each platform decides what it accepts", supply)
        self.assertIn("target public allocation", supply)
        self.assertIn("Do not say 400,000,000 GCA is fully circulating", supply)
        self.assertIn("Do not say the 600,000,000 GCA reserve is locked", supply)
        self.assertIn("Do not say the reserve is multisig-controlled", supply)
        self.assertIn("Do not claim the reserve provides price support", supply)
        self.assertIn('href="markets.html"', supply)
        self.assertIn('href="status.html"', supply)
        self.assertIn('href="listing-kit.html"', supply)

    def test_security_page_summarizes_contract_controls_and_audit_status(self):
        security = (ROOT / "site" / "security.html").read_text()

        self.assertIn("GCA Security", security)
        self.assertIn("verified contract controls", security)
        self.assertIn("Verified on BaseScan", security)
        self.assertIn("Fixed at 1B GCA", security)
        self.assertIn("Third-Party Audit", security)
        self.assertIn("Not completed", security)
        self.assertIn("No mint function", security)
        self.assertIn("No transfer tax", security)
        self.assertIn("No blacklist", security)
        self.assertIn("No owner role", security)
        self.assertIn("No proxy", security)
        self.assertIn("No withdrawal path", security)
        self.assertIn("internal engineering review was completed on 2026-05-08", security)
        self.assertIn("No critical, high, medium, or low severity contract issues", security)
        self.assertIn("Source SHA-256", security)
        self.assertIn("6ba294fe0f6e20485f90297eede83ce620291ab525c92abb3bcf6547d1cf4cce", security)
        self.assertIn("No independent third-party audit has been completed", security)
        self.assertIn("Quote requests were submitted to QuillAudits, Hacken, and OpenZeppelin on 2026-05-10", security)
        self.assertIn("then deferred by owner decision", security)
        self.assertIn("Residual risks", security)
        self.assertIn("starter-depth liquidity", security)
        self.assertIn("false-positive report was submitted", security)
        self.assertIn("does not prove removal", security)
        self.assertIn("Safe to say: source verified, fixed supply, no mint function", security)
        self.assertIn("Do not say: third-party audited, externally audited, audit-approved", security)
        self.assertIn(MAINNET_ADDRESS, security)
        self.assertIn('href="status.html"', security)
        self.assertIn('href="faq.html"', security)
        self.assertIn('href="supply.html"', security)
        self.assertIn('href="listing-kit.html"', security)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, security)

    def test_risk_page_centralizes_public_disclosures(self):
        risk = (ROOT / "site" / "risk.html").read_text()

        self.assertIn("GCA Risk Disclosures", risk)
        self.assertIn("does not tell anyone to buy or sell", risk)
        self.assertIn("Stage", risk)
        self.assertIn("Early-stage", risk)
        self.assertIn("Starter depth", risk)
        self.assertIn("No third-party audit", risk)
        self.assertIn("Owner-controlled", risk)
        self.assertIn("Market and Liquidity", risk)
        self.assertIn("starter-depth liquidity only", risk)
        self.assertIn("slippage can be high", risk)
        self.assertIn("Wallet and DEX Warnings", risk)
        self.assertIn("Blockaid false-positive report was submitted on 2026-05-10", risk)
        self.assertIn("report submission does not mean warnings have been removed", risk)
        self.assertIn("Audit Status", risk)
        self.assertIn("no independent third-party audit report exists", risk)
        self.assertIn("Reserve Custody", risk)
        self.assertIn("600,000,000 GCA owner reserve", risk)
        self.assertIn("not locked, vested, or multisig-controlled", risk)
        self.assertIn("Utility Readiness", risk)
        self.assertIn("not public self-service", risk)
        self.assertIn("Supply Reporting", risk)
        self.assertIn("1,000,000,000 GCA", risk)
        self.assertIn("40/60 allocation", risk)
        self.assertIn("Listing and Metadata", risk)
        self.assertIn("GeckoTerminal token information was approved on 2026-05-11", risk)
        self.assertIn("BaseScan token profile is still awaiting review", risk)
        self.assertIn("Do not claim price support", risk)
        self.assertIn("Do not claim third-party audit completion", risk)
        self.assertIn("Do not claim wallet warnings are removed", risk)
        self.assertIn("Do not use artificial volume, self-trading, wash trading, or fake activity", risk)
        self.assertIn("Safer Public Framing", risk)
        self.assertIn("Base Mainnet chain ID 8453", risk)
        self.assertIn("official GCA/USDT pool", risk)
        self.assertIn('href="status.html"', risk)
        self.assertIn('href="security.html"', risk)
        self.assertIn('href="supply.html"', risk)
        self.assertIn('href="markets.html"', risk)
        self.assertIn('href="faq.html"', risk)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, risk)

    def test_faq_page_answers_common_user_questions_safely(self):
        faq = (ROOT / "site" / "faq.html").read_text()

        self.assertIn("GCA FAQ", faq)
        self.assertIn("Base Mainnet / 8453", faq)
        self.assertIn(MAINNET_ADDRESS, faq)
        self.assertIn(OFFICIAL_POOL_ADDRESS, faq)
        self.assertIn("Why does my wallet not show GCA?", faq)
        self.assertIn("import the token manually", faq)
        self.assertIn("Why is there no price display?", faq)
        self.assertIn("Wallets and data platforms decide when to index token prices", faq)
        self.assertIn("Why do I see a high-risk warning?", faq)
        self.assertIn("Blockaid false-positive report was submitted on 2026-05-10", faq)
        self.assertIn("report submission does not mean the warning has been removed", faq)
        self.assertIn("Is GCA externally audited?", faq)
        self.assertIn("no independent third-party audit report has been completed", faq)
        self.assertIn("Why does BaseScan show 1B supply?", faq)
        self.assertIn("Transfers, reserve separation, and liquidity additions do not reduce totalSupply", faq)
        self.assertIn("What is the 40/60 split?", faq)
        self.assertIn("400,000,000 GCA", faq)
        self.assertIn("600,000,000 GCA", faq)
        self.assertIn("Is the reserve locked?", faq)
        self.assertIn("normal owner-controlled wallet", faq)
        self.assertIn("If someone buys GCA, does my wallet balance go down?", faq)
        self.assertIn("they receive tokens from the pool inventory", faq)
        self.assertIn("Where do payments go when someone buys?", faq)
        self.assertIn("the quote asset goes into the pool", faq)
        self.assertIn("How can GCA build stronger market quality?", faq)
        self.assertIn("Artificial volume, self-trading, and fake activity should not be used", faq)
        self.assertIn("Which pool should be shared publicly?", faq)
        self.assertIn("Public Claim Boundaries", faq)
        self.assertIn("Do not describe GCA as externally audited", faq)
        self.assertIn("Do not claim BaseScan token profile approval", faq)
        self.assertIn('href="buy.html"', faq)
        self.assertIn('href="markets.html"', faq)
        self.assertIn('href="supply.html"', faq)
        self.assertIn('href="status.html"', faq)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, faq)

    def test_status_page_centralizes_public_verification(self):
        status = (ROOT / "site" / "status.html").read_text()
        index = (ROOT / "site" / "index.html").read_text()
        buy = (ROOT / "site" / "buy.html").read_text()
        members = (ROOT / "site" / "members.html").read_text()
        utility = (ROOT / "site" / "utility.html").read_text()
        whitepaper = (ROOT / "site" / "whitepaper.html").read_text()
        markets = (ROOT / "site" / "markets.html").read_text()
        supply = (ROOT / "site" / "supply.html").read_text()
        security = (ROOT / "site" / "security.html").read_text()
        risk = (ROOT / "site" / "risk.html").read_text()
        faq = (ROOT / "site" / "faq.html").read_text()
        verify = (ROOT / "site" / "verify.html").read_text()

        self.assertIn("GCA Project Status", status)
        self.assertIn("Base Mainnet / chainId 8453", status)
        self.assertIn(MAINNET_ADDRESS, status)
        self.assertIn(OFFICIAL_POOL_ADDRESS, status)
        self.assertIn(BASE_USDT_ADDRESS, status)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, status)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, status)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, status)
        self.assertIn("Approved 2026-05-11", status)
        self.assertIn("Submitted, awaiting review", status)
        self.assertIn("BaseScan public token profile publication", status)
        self.assertIn("Wallet warning removal after Blockaid report", status)
        self.assertIn("CoinGecko tracked listing", status)
        self.assertIn("CoinMarketCap tracked listing", status)
        self.assertIn("No third-party audit has been completed", status)
        self.assertIn("600,000,000 GCA", status)
        self.assertIn("normal owner-controlled wallet", status)
        self.assertIn("Do not say the BaseScan token profile is approved", status)
        self.assertIn("Do not say GCA is externally audited", status)
        self.assertIn("Do not describe liquidity as deep", status)
        self.assertIn("Do not claim price support", status)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, status)

        for page in (index, buy, markets, supply, security, risk, faq, members, utility, whitepaper, verify):
            self.assertIn('href="status.html"', page)
            self.assertIn('href="listing-kit.html"', page)
            self.assertIn('href="markets.html"', page)
            self.assertIn('href="supply.html"', page)
            self.assertIn('href="security.html"', page)
            self.assertIn('href="risk.html"', page)
            self.assertIn('href="faq.html"', page)

    def test_listing_kit_and_project_json_are_copyable(self):
        kit = (ROOT / "site" / "listing-kit.html").read_text()
        project = json.loads((ROOT / "site" / "project.json").read_text())

        self.assertIn("GCA Listing Kit", kit)
        self.assertIn("Machine-Readable JSON", kit)
        self.assertIn("project.json", kit)
        self.assertIn("Token List JSON", kit)
        self.assertIn("tokenlist.json", kit)
        self.assertIn("Member Program JSON", kit)
        self.assertIn(MEMBER_PROGRAM_URL, kit)
        self.assertIn("Well-Known JSON", kit)
        self.assertIn(WELL_KNOWN_TOKEN_URL, kit)
        self.assertIn(SECURITY_CONTACT_URL, kit)
        self.assertIn("Market page", kit)
        self.assertIn(MARKET_PAGE_URL, kit)
        self.assertIn("Verify page", kit)
        self.assertIn(VERIFY_PAGE_URL, kit)
        self.assertIn("Supply page", kit)
        self.assertIn(SUPPLY_PAGE_URL, kit)
        self.assertIn("Security page", kit)
        self.assertIn(SECURITY_PAGE_URL, kit)
        self.assertIn("Risk page", kit)
        self.assertIn(RISK_PAGE_URL, kit)
        self.assertIn("FAQ", kit)
        self.assertIn(FAQ_URL, kit)
        self.assertIn("Token name", kit)
        self.assertIn("GCA / Go China Access", kit)
        self.assertIn(MAINNET_ADDRESS, kit)
        self.assertIn(OFFICIAL_POOL_ADDRESS, kit)
        self.assertIn(BASE_USDT_ADDRESS, kit)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, kit)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, kit)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, kit)
        self.assertIn("Short Description", kit)
        self.assertIn("Long Description", kit)
        self.assertIn("BaseScan", kit)
        self.assertIn("submitted and awaiting review", kit)
        self.assertIn("GeckoTerminal", kit)
        self.assertIn("approved on 2026-05-11", kit)
        self.assertIn("CoinGecko / CMC", kit)
        self.assertIn("not submitted", kit)
        self.assertIn("Do Not Claim", kit)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, kit)

        self.assertEqual(project["projectName"], "GCA")
        self.assertEqual(project["network"], "Base Mainnet")
        self.assertEqual(project["chainId"], 8453)
        self.assertEqual(project["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(project["verifyUrl"], VERIFY_PAGE_URL)
        self.assertEqual(project["listingKitUrl"], "https://gcagochina.com/listing-kit.html")
        self.assertEqual(project["tokenListUrl"], "https://gcagochina.com/tokenlist.json")
        self.assertEqual(project["wellKnownTokenIdentityUrl"], WELL_KNOWN_TOKEN_URL)
        self.assertEqual(project["securityContactUrl"], SECURITY_CONTACT_URL)
        self.assertEqual(project["lastUpdated"], "2026-05-12")
        self.assertEqual(project["marketPageUrl"], MARKET_PAGE_URL)
        self.assertEqual(project["supplyPageUrl"], SUPPLY_PAGE_URL)
        self.assertEqual(project["securityPageUrl"], SECURITY_PAGE_URL)
        self.assertEqual(project["riskPageUrl"], RISK_PAGE_URL)
        self.assertEqual(project["faqUrl"], FAQ_URL)
        self.assertEqual(project["memberProgramRulesUrl"], MEMBER_PROGRAM_URL)
        self.assertEqual(project["memberProgram"]["status"], "rules-published-public-claim-not-connected")
        self.assertEqual(project["memberProgram"]["holderBonus"]["creditExpiry"], "180 days after ledger activation unless a later published policy extends it")
        self.assertIn("ENTRY_READY signal review", project["memberProgram"]["holderBonus"]["spendScope"])
        self.assertEqual(project["memberProgram"]["gcaMember"]["refreshCadence"], "30 days after activation, or earlier if the user requests a manual recheck")
        self.assertIn("priority support", project["memberProgram"]["gcaMember"]["accessScope"])
        self.assertIn("not a guarantee", project["memberProgram"]["supportWorkflow"]["targetFirstResponse"])
        self.assertEqual(project["market"]["officialPair"], "GCA/USDT")
        self.assertEqual(project["market"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(project["market"]["quoteAssetAddress"], BASE_USDT_ADDRESS)
        self.assertEqual(project["market"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(project["market"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(project["market"]["officialSwapUrl"], OFFICIAL_SWAP_URL)
        self.assertEqual(project["supplyDisclosure"]["ownerReserveWallet"], RESERVE_WALLET)
        self.assertEqual(project["platformStatus"]["baseScanTokenProfile"], "submitted-awaiting-review")
        self.assertEqual(project["platformStatus"]["geckoTerminalTokenInfo"], "approved-2026-05-11")
        self.assertEqual(project["platformStatus"]["thirdPartyAudit"], "not-completed")

    def test_token_list_json_is_official_and_conservative(self):
        tokenlist = json.loads((ROOT / "site" / "tokenlist.json").read_text())
        self.assertEqual(tokenlist["name"], "GCA Official Token List")
        self.assertEqual(tokenlist["timestamp"], "2026-05-12T00:00:00+07:00")
        self.assertEqual(tokenlist["version"], {"major": 1, "minor": 0, "patch": 0})
        self.assertIn("base", tokenlist["keywords"])
        self.assertEqual(len(tokenlist["tokens"]), 1)

        token = tokenlist["tokens"][0]
        self.assertEqual(token["chainId"], 8453)
        self.assertEqual(token["address"], MAINNET_ADDRESS)
        self.assertEqual(token["name"], "GCA")
        self.assertEqual(token["symbol"], "GCA")
        self.assertEqual(token["decimals"], 18)
        self.assertEqual(token["logoURI"], "https://gcagochina.com/assets/gca-logo.png")

        extensions = token["extensions"]
        self.assertEqual(extensions["website"], "https://gcagochina.com/")
        self.assertEqual(extensions["verify"], VERIFY_PAGE_URL)
        self.assertEqual(extensions["statusPage"], "https://gcagochina.com/status.html")
        self.assertEqual(extensions["listingKit"], "https://gcagochina.com/listing-kit.html")
        self.assertEqual(extensions["projectJson"], "https://gcagochina.com/project.json")
        self.assertEqual(extensions["wellKnownTokenIdentity"], WELL_KNOWN_TOKEN_URL)
        self.assertEqual(extensions["securityContact"], SECURITY_CONTACT_URL)
        self.assertEqual(extensions["marketPage"], MARKET_PAGE_URL)
        self.assertEqual(extensions["supplyPage"], SUPPLY_PAGE_URL)
        self.assertEqual(extensions["securityPage"], SECURITY_PAGE_URL)
        self.assertEqual(extensions["riskPage"], RISK_PAGE_URL)
        self.assertEqual(extensions["faq"], FAQ_URL)
        self.assertEqual(extensions["memberProgramRules"], MEMBER_PROGRAM_URL)
        self.assertEqual(extensions["officialTelegram"], TELEGRAM_URL)
        self.assertEqual(extensions["geckoTerminal"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(extensions["dexScreener"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(extensions["officialSwap"], OFFICIAL_SWAP_URL)
        self.assertEqual(extensions["officialPair"], "GCA/USDT")
        self.assertEqual(extensions["officialPool"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(extensions["geckoTerminalStatus"], "approved-2026-05-11")
        self.assertEqual(extensions["baseScanTokenProfileStatus"], "submitted-awaiting-review")
        self.assertEqual(extensions["thirdPartyAuditStatus"], "not-completed")
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, json.dumps(tokenlist))

    def test_public_materials_avoid_investment_promises(self):
        paths = [
            ROOT / "site" / "index.html",
            ROOT / "site" / "verify.html",
            ROOT / "site" / "buy.html",
            ROOT / "site" / "markets.html",
            ROOT / "site" / "supply.html",
            ROOT / "site" / "security.html",
            ROOT / "site" / "risk.html",
            ROOT / "site" / "faq.html",
            ROOT / "site" / "status.html",
            ROOT / "site" / "listing-kit.html",
            ROOT / "site" / "members.html",
            ROOT / "site" / "member-program.json",
            ROOT / "site" / "utility.html",
            ROOT / "site" / ".well-known" / "gca-token.json",
            ROOT / "site" / ".well-known" / "security.txt",
            ROOT / "docs" / "whitepaper.md",
            ROOT / "docs" / "mainnet_public_profile.md",
            ROOT / "launch" / "basescan_token_submission.md",
            ROOT / "launch" / "basescan_review_followup.md",
            ROOT / "launch" / "token_allocation_plan.md",
            ROOT / "launch" / "liquidity_pool_runbook.md",
            ROOT / "launch" / "launch_status.md",
            ROOT / "launch" / "data_platform_package.md",
            ROOT / "launch" / "external_review_followup_tracker.md",
            ROOT / "launch" / "geckoterminal_update_runbook.md",
            ROOT / "launch" / "member_pre_registration_runbook.md",
            ROOT / "launch" / "telegram_channel_runbook.md",
            ROOT / "launch" / "telegram_pinned_buy_announcement.md",
        ]
        forbidden = re.compile(r"\b(guaranteed returns?|profit sharing|risk[- ]?free|稳赚|保本|拉盘|炒币)\b", re.I)
        for path in paths:
            with self.subTest(path=path.name):
                self.assertIsNone(forbidden.search(path.read_text()))

    def test_basescan_submission_has_required_public_placeholders(self):
        submission = (ROOT / "launch" / "basescan_token_submission.md").read_text()
        self.assertIn("https://gcagochina.com/", submission)
        self.assertIn("Official contact email", submission)
        self.assertIn("cxy070800@gmail.com", submission)
        self.assertIn(TELEGRAM_URL, submission)
        self.assertIn("Gmail address", submission)
        self.assertIn("Submitted from the owner's browser session on 2026-05-09", submission)
        self.assertIn("deployer-wallet ownership verification were included", submission)
        self.assertIn("publicly listed on the official website", submission)
        self.assertIn("Public logo download URL", submission)
        self.assertNotIn("https://x.com/GCAgochina", submission)
        self.assertIn("https://basescan.org/tokenupdate/", submission)
        self.assertIn(MAINNET_ADDRESS, submission)

    def test_basescan_review_followup_is_actionable(self):
        followup = (ROOT / "launch" / "basescan_review_followup.md").read_text()
        self.assertIn("awaiting BaseScan review", followup)
        self.assertIn("cxy070800@gmail.com", followup)
        self.assertIn("Base Mainnet", followup)
        self.assertIn("Chain ID: 8453", followup)
        self.assertIn(MAINNET_ADDRESS, followup)
        self.assertIn("If BaseScan Approves", followup)
        self.assertIn("If BaseScan Requests Changes", followup)
        self.assertIn("Reply Template", followup)
        self.assertIn("Do not describe the BaseScan token profile as complete", followup)
        self.assertIn(VERIFY_PAGE_URL, followup)
        self.assertIn("Official verify page", followup)
        self.assertIn("https://gcagochina.com/status.html", followup)
        self.assertIn("Official GCA/USDT pool", followup)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, followup)

    def test_basescan_form_values_are_copyable(self):
        values = json.loads((ROOT / "launch" / "basescan_form_values.json").read_text())
        self.assertEqual(values["network"], "Base Mainnet")
        self.assertEqual(values["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(values["website"], "https://gcagochina.com/")
        self.assertEqual(values["utilityThesisUrl"], "https://gcagochina.com/utility.html")
        self.assertEqual(values["logoUrl"], "https://gcagochina.com/assets/gca-logo.svg")
        self.assertEqual(values["whitepaperUrl"], "https://gcagochina.com/whitepaper.html")
        self.assertEqual(values["officialEmail"], "cxy070800@gmail.com")
        self.assertIn("Gmail address", values["officialEmailNote"])
        self.assertEqual(values["targetPublicAllocation"], "400000000")
        self.assertEqual(values["targetPublicAllocationPercent"], 40)
        self.assertEqual(values["ownerHeldReserve"], "600000000")
        self.assertEqual(values["ownerHeldReservePercent"], 60)
        self.assertEqual(values["ownerReserveWallet"], RESERVE_WALLET)
        self.assertEqual(values["ownerReserveTransferTxs"], [RESERVE_TX, SECOND_RESERVE_TX])
        self.assertIn("normal owner-controlled wallet", values["ownerReserveCustodyNote"])
        self.assertIn("Go China Access", values["description"])
        self.assertIn("Go China macro narrative", values["description"])
        self.assertIn("non-custodial quant risk tools", values["description"])
        self.assertIn("ENTRY_READY signal review", values["description"])
        self.assertEqual(values["submissionStatus"], "submitted")
        self.assertEqual(values["reviewStatus"], "awaiting BaseScan review")
        self.assertEqual(values["socialLinks"][0]["platform"], "Telegram")
        self.assertEqual(values["socialLinks"][0]["url"], TELEGRAM_URL)
        self.assertIn("after the initial BaseScan submission", values["socialLinkNote"])
        self.assertEqual(values["officialMarketPool"]["pair"], "GCA/USDT")
        self.assertEqual(values["officialMarketPool"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(values["officialMarketPool"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["officialMarketPool"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(values["officialMarketPool"]["officialSwapUrl"], OFFICIAL_SWAP_URL)

    def test_token_allocation_plan_records_owner_reserve(self):
        plan = json.loads((ROOT / "launch" / "token_allocation_plan.json").read_text())
        doc = (ROOT / "launch" / "token_allocation_plan.md").read_text()
        self.assertEqual(plan["totalSupply"], "1000000000")
        self.assertEqual(plan["allocationPlanStatus"], "owner-reserve-increased")
        self.assertEqual(plan["allocations"][0]["amount"], "400000000")
        self.assertEqual(plan["allocations"][0]["percent"], 40)
        self.assertEqual(plan["allocations"][1]["amount"], "600000000")
        self.assertEqual(plan["allocations"][1]["percent"], 60)
        self.assertEqual(plan["allocations"][1]["holder"], RESERVE_WALLET)
        self.assertEqual(plan["allocations"][1]["transferTransactionHashes"], [RESERVE_TX, SECOND_RESERVE_TX])
        self.assertEqual(plan["ownerReserveWalletBalanceGca"], "600000000")
        self.assertEqual(plan["executedOwnerReserveTransfers"][1]["to"], RESERVE_WALLET)
        self.assertEqual(plan["executedOwnerReserveTransfers"][1]["transactionHash"], SECOND_RESERVE_TX)
        self.assertIn("owner/founder", plan["allocations"][1]["notes"])
        self.assertIn("target allocation", doc)
        self.assertIn("600,000,000 GCA", doc)
        self.assertIn("not be described as circulating", doc)
        self.assertIn("not a lock, vesting contract, or Safe multisig", doc)
        self.assertIn(RESERVE_WALLET, doc)
        self.assertIn(RESERVE_TX, doc)
        self.assertIn(SECOND_RESERVE_TX, doc)
        self.assertIn(MAINNET_ADDRESS, doc)
        self.assertEqual(plan["officialMarketPool"]["pair"], "GCA/USDT")
        self.assertEqual(plan["officialMarketPool"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, doc)

    def test_public_materials_do_not_overstate_basescan_review(self):
        paths = [
            ROOT / "site" / "index.html",
            ROOT / "site" / "verify.html",
            ROOT / "site" / "buy.html",
            ROOT / "site" / "markets.html",
            ROOT / "site" / "supply.html",
            ROOT / "site" / "security.html",
            ROOT / "site" / "risk.html",
            ROOT / "site" / "faq.html",
            ROOT / "site" / "status.html",
            ROOT / "site" / "listing-kit.html",
            ROOT / "site" / "whitepaper.html",
            ROOT / "site" / "utility.html",
            ROOT / "docs" / "whitepaper.md",
            ROOT / "docs" / "mainnet_public_profile.md",
            ROOT / "launch" / "launch_status.md",
        ]
        forbidden = [
            "BaseScan profile complete",
            "BaseScan approved",
            "BaseScan token profile is complete",
            "BaseScan token profile has been accepted",
            "BaseScan token profile is live",
        ]
        for path in paths:
            text = path.read_text()
            with self.subTest(path=path.name):
                for phrase in forbidden:
                    self.assertNotIn(phrase, text)

    def test_liquidity_runbook_records_execution(self):
        runbook = (ROOT / "launch" / "liquidity_pool_runbook.md").read_text()
        self.assertIn("Executed on Base Mainnet.", runbook)
        self.assertIn("5087977", runbook)
        self.assertIn("0xef94e020c8b431151b789ca3e96c45ab0c18d20d15bf8d7d543630f1370fc158", runbook)
        self.assertIn(MAINNET_ADDRESS, runbook)

    def test_liquidity_plan_has_selected_mainnet_defaults(self):
        plan = json.loads((ROOT / "launch" / "liquidity_plan.json").read_text())
        self.assertEqual(plan["status"], "executed")
        self.assertEqual(plan["network"], "Base Mainnet")
        self.assertEqual(plan["chainId"], 8453)
        self.assertEqual(plan["protocolVersion"], "v3")
        self.assertEqual(plan["feeTier"], "1%")
        self.assertEqual(plan["selectedPlan"]["gcaAmount"], "100000")
        self.assertEqual(plan["selectedPlan"]["ethAmount"], "0.001")
        self.assertEqual(plan["selectedPlan"]["impliedFullyDilutedValueEth"], "10")
        self.assertEqual(plan["pair"]["baseToken"]["address"], MAINNET_ADDRESS)
        self.assertEqual(plan["execution"]["positionTokenId"], "5087977")
        self.assertEqual(plan["execution"]["poolAddress"], "0x79fc0b367adbd79118c664f5ee27eb6ff8cb69ff")

    def test_liquidity_deployment_record_is_on_base_mainnet(self):
        record = json.loads((ROOT / "deployments" / "base-mainnet-gca-liquidity.json").read_text())
        self.assertEqual(record["status"], "executed")
        self.assertEqual(record["network"], "Base Mainnet")
        self.assertEqual(record["chainId"], 8453)
        self.assertEqual(record["tokenId"], "5087977")
        self.assertEqual(record["transactionHash"], "0xef94e020c8b431151b789ca3e96c45ab0c18d20d15bf8d7d543630f1370fc158")
        self.assertEqual(record["tokens"]["token0"]["address"], MAINNET_ADDRESS)
        self.assertEqual(record["tokens"]["token1"]["symbol"], "WETH")
        self.assertEqual(record["position"]["tickLower"], -887200)
        self.assertEqual(record["position"]["tickUpper"], 887200)

    def test_launch_status_separates_done_from_external_blockers(self):
        status = (ROOT / "launch" / "launch_status.md").read_text()
        self.assertIn("## Done", status)
        self.assertIn("## Needs Owner Input Or External Service", status)
        self.assertIn("https://gcagochina.com/", status)
        self.assertIn("Public site health-check script prepared", status)
        self.assertIn("tools/check_public_site.py", status)
        self.assertIn("GitHub Actions public site health-check workflow prepared", status)
        self.assertIn("daily schedule", status)
        self.assertIn("DNS records for `gcagochina.com`", status)
        self.assertIn("GitHub Pages HTTPS certificate issued", status)
        self.assertIn("GitHub Actions publishing workflow prepared", status)
        self.assertIn("sync `site/` to the `gh-pages` branch", status)
        self.assertIn("Data platform submission package prepared", status)
        self.assertIn("External review follow-up tracker prepared", status)
        self.assertIn("launch/external_review_followup_tracker.md", status)
        self.assertIn("GeckoTerminal token info update runbook prepared", status)
        self.assertIn("GeckoTerminal token info update submitted on 2026-05-09", status)
        self.assertIn("GeckoTerminal token information update approved on 2026-05-11", status)
        self.assertIn("Public project status page prepared", status)
        self.assertIn("Public listing kit and machine-readable project JSON prepared", status)
        self.assertIn("Official token list JSON prepared", status)
        self.assertIn("Public well-known token identity JSON and security contact files prepared", status)
        self.assertIn(WELL_KNOWN_TOKEN_URL, status)
        self.assertIn(SECURITY_CONTACT_URL, status)
        self.assertNotIn("Wait for GeckoTerminal review", status)
        self.assertIn(TELEGRAM_URL, status)
        self.assertIn("Telegram channel runbook prepared", status)
        self.assertIn("First official Telegram announcement pinned on 2026-05-10", status)
        self.assertIn("Official buy guide page prepared", status)
        self.assertIn("https://gcagochina.com/buy.html", status)
        self.assertIn("Official market page prepared", status)
        self.assertIn("https://gcagochina.com/markets.html", status)
        self.assertIn("centralize the GCA/USDT pool", status)
        self.assertIn("Official supply and reserve page prepared", status)
        self.assertIn("https://gcagochina.com/supply.html", status)
        self.assertIn("40/60 target allocation", status)
        self.assertIn("Official security page prepared", status)
        self.assertIn("https://gcagochina.com/security.html", status)
        self.assertIn("no mint, no tax, no blacklist, no admin controls", status)
        self.assertIn("Official risk disclosure page prepared", status)
        self.assertIn("https://gcagochina.com/risk.html", status)
        self.assertIn("starter-liquidity, wallet-warning, audit, reserve-custody", status)
        self.assertIn("Official FAQ page prepared", status)
        self.assertIn("https://gcagochina.com/faq.html", status)
        self.assertIn("wallet import, price display, risk warning", status)
        self.assertIn("Public member program rules prepared", status)
        self.assertIn(MEMBER_PROGRAM_URL, status)
        self.assertIn("180-day credit expiry", status)
        self.assertIn("30-day member refresh cadence", status)
        self.assertIn("support status workflow", status)
        self.assertIn("Telegram replacement pinned buy announcement template prepared", status)
        self.assertIn("launch/telegram_pinned_buy_announcement.md", status)
        self.assertIn("Replace the Telegram pinned message", status)
        self.assertIn("buy/sell functional swap tests observed on 2026-05-10", status)
        self.assertIn("launch/swap_test_evidence.md", status)
        self.assertIn("Blockaid false-positive report submitted on 2026-05-10", status)
        self.assertIn("Blockaid follow-up context updated to use the current GCA/USDT pool", status)
        self.assertIn("does not mean the warning has been removed", status)
        self.assertIn("must not be described as proof of organic volume", status)
        self.assertIn("Third-party audit quote requests submitted to QuillAudits, Hacken, and OpenZeppelin on 2026-05-10", status)
        self.assertIn("Owner decided on 2026-05-10 to defer third-party audit", status)
        self.assertIn("Archive any audit quote replies", status)
        self.assertIn("Use `launch/external_review_followup_tracker.md`", status)
        self.assertIn("quote submission is not an audit", status)
        self.assertNotIn("Pin the first Telegram announcement manually", status)
        self.assertNotIn("wait for GitHub Pages HTTPS to become active", status)
        self.assertIn("Base Mainnet / chainId 8453", status)
        self.assertIn("Base Sepolia / chainId 84532", status)
        self.assertIn(RESERVE_WALLET, status)
        self.assertIn(RESERVE_TX, status)
        self.assertIn(SECOND_RESERVE_TX, status)

    def test_telegram_channel_runbook_records_official_channel(self):
        runbook = (ROOT / "launch" / "telegram_channel_runbook.md").read_text()
        self.assertIn(TELEGRAM_URL, runbook)
        self.assertIn("First public announcement: posted on 2026-05-09", runbook)
        self.assertIn("Pin status: confirmed on 2026-05-10", runbook)
        self.assertIn("Recommended replacement pinned buy announcement prepared", runbook)
        self.assertIn("launch/telegram_pinned_buy_announcement.md", runbook)
        self.assertIn(MAINNET_ADDRESS, runbook)
        self.assertIn("Official GCA/USDT pool", runbook)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, runbook)
        self.assertIn("No third-party audit has been completed", runbook)
        self.assertIn("starter-depth only", runbook)
        self.assertIn("Do not submit the frozen X account", runbook)

    def test_data_platform_package_is_copyable_and_conservative(self):
        package = (ROOT / "launch" / "data_platform_package.md").read_text()
        values = json.loads((ROOT / "launch" / "data_platform_form_values.json").read_text())

        self.assertIn("DEX Screener", package)
        self.assertIn("GeckoTerminal", package)
        self.assertIn("CoinGecko", package)
        self.assertIn("CoinMarketCap", package)
        self.assertIn("https://gcagochina.com/", package)
        self.assertIn(VERIFY_PAGE_URL, package)
        self.assertIn("https://gcagochina.com/status.html", package)
        self.assertIn("https://gcagochina.com/listing-kit.html", package)
        self.assertIn("https://gcagochina.com/project.json", package)
        self.assertIn("https://gcagochina.com/tokenlist.json", package)
        self.assertIn(WELL_KNOWN_TOKEN_URL, package)
        self.assertIn(SECURITY_CONTACT_URL, package)
        self.assertIn("launch/external_review_followup_tracker.md", package)
        self.assertIn("External Review Follow-Up Tracker", package)
        self.assertIn("https://gcagochina.com/buy.html", package)
        self.assertIn("https://gcagochina.com/markets.html", package)
        self.assertIn("https://gcagochina.com/supply.html", package)
        self.assertIn("https://gcagochina.com/security.html", package)
        self.assertIn("https://gcagochina.com/risk.html", package)
        self.assertIn("https://gcagochina.com/faq.html", package)
        self.assertIn("https://gcagochina.com/members.html", package)
        self.assertIn("https://gcagochina.com/utility.html", package)
        self.assertIn("https://gcagochina.com/assets/gca-logo.svg", package)
        self.assertIn("https://gcagochina.com/whitepaper.html", package)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, package)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, package)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, package)
        self.assertIn(OFFICIAL_SWAP_URL, package)
        self.assertIn("GCA/USDT", package)
        self.assertIn("GeckoTerminal token info update: approved on 2026-05-11", package)
        self.assertIn("starter-depth only", package)
        self.assertIn("buy/sell functional swap tests were observed on 2026-05-10", package)
        self.assertIn("not as proof of organic demand or strong liquidity", package)
        self.assertIn("not completed", package)
        self.assertIn("quote requests were submitted on 2026-05-10 and then deferred by owner decision", package)
        self.assertIn("frozen", package)
        self.assertIn(TELEGRAM_URL, package)
        self.assertIn(MAINNET_ADDRESS, package)
        self.assertIn(RESERVE_WALLET, package)
        self.assertIn(RESERVE_TX, package)
        self.assertIn(SECOND_RESERVE_TX, package)

        self.assertEqual(values["packageStatus"], "prepared")
        self.assertEqual(values["chainId"], 8453)
        self.assertEqual(values["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(values["website"], "https://gcagochina.com/")
        self.assertEqual(values["verifyUrl"], VERIFY_PAGE_URL)
        self.assertEqual(values["statusPageUrl"], "https://gcagochina.com/status.html")
        self.assertEqual(values["listingKitUrl"], "https://gcagochina.com/listing-kit.html")
        self.assertEqual(values["projectJsonUrl"], "https://gcagochina.com/project.json")
        self.assertEqual(values["tokenListUrl"], "https://gcagochina.com/tokenlist.json")
        self.assertEqual(values["wellKnownTokenIdentityUrl"], WELL_KNOWN_TOKEN_URL)
        self.assertEqual(values["securityContactUrl"], SECURITY_CONTACT_URL)
        self.assertEqual(values["buyGuideUrl"], "https://gcagochina.com/buy.html")
        self.assertEqual(values["marketPageUrl"], MARKET_PAGE_URL)
        self.assertEqual(values["supplyPageUrl"], SUPPLY_PAGE_URL)
        self.assertEqual(values["securityPageUrl"], SECURITY_PAGE_URL)
        self.assertEqual(values["riskPageUrl"], RISK_PAGE_URL)
        self.assertEqual(values["faqUrl"], FAQ_URL)
        self.assertEqual(values["memberPreRegistrationUrl"], "https://gcagochina.com/members.html")
        self.assertEqual(values["memberProgramRulesUrl"], MEMBER_PROGRAM_URL)
        self.assertEqual(values["utilityThesisUrl"], "https://gcagochina.com/utility.html")
        self.assertEqual(values["logoUrl"], "https://gcagochina.com/assets/gca-logo.svg")
        self.assertEqual(values["utilityPositioning"]["connectedProduct"], "Web3 Radar non-custodial quant risk toolkit")
        self.assertIn("ENTRY_READY signal review", values["utilityPositioning"]["suitableUtility"])
        self.assertIn("one-time 100 Web3 Radar utility credits ledger record for each registered user who verifies one wallet holding at least 10000 GCA", values["utilityPositioning"]["suitableUtility"])
        self.assertIn("GCA Member status in the Web3 Radar member ledger for each registered user who verifies one wallet holding at least 1000000 GCA", values["utilityPositioning"]["suitableUtility"])
        self.assertEqual(values["utilityPositioning"]["status"], "local-verified-access-backend-ready-public-claim-not-connected")
        self.assertEqual(values["utilityPositioning"]["plannedFirstCampaign"]["registeredUserLimit"], "one bonus per registered user")
        self.assertEqual(values["utilityPositioning"]["plannedFirstCampaign"]["minimumHolding"], "10000 GCA")
        self.assertEqual(values["utilityPositioning"]["plannedFirstCampaign"]["bonus"], "100 Web3 Radar utility credits")
        self.assertEqual(values["utilityPositioning"]["plannedFirstCampaign"]["creditExpiry"], "180 days after ledger activation unless a later published policy extends it")
        self.assertIn("risk-control bypass", values["utilityPositioning"]["plannedFirstCampaign"]["notCreditUse"])
        self.assertEqual(values["utilityPositioning"]["plannedMemberTier"]["tierName"], "GCA Member")
        self.assertEqual(values["utilityPositioning"]["plannedMemberTier"]["minimumHolding"], "1000000 GCA")
        self.assertEqual(values["utilityPositioning"]["plannedMemberTier"]["refreshCadence"], "30 days after activation, or earlier if the user requests a manual recheck")
        self.assertIn("higher utility credit limits", values["utilityPositioning"]["plannedMemberTier"]["memberAccess"])
        self.assertIn("guaranteed lifetime access", values["utilityPositioning"]["plannedMemberTier"]["notMemberAccess"])
        self.assertEqual(values["utilityPositioning"]["supportWorkflow"]["contactEmail"], "GCAgochina@outlook.com")
        self.assertIn("not a guarantee", values["utilityPositioning"]["supportWorkflow"]["targetFirstResponse"])
        self.assertIn("ledger_recorded", values["utilityPositioning"]["supportWorkflow"]["reviewStatuses"])
        self.assertIn("platform revenue distribution", values["utilityPositioning"]["notUtility"])
        self.assertEqual(values["liquidity"]["dex"], "Uniswap v4")
        self.assertEqual(values["liquidity"]["pair"], "GCA/USDT")
        self.assertEqual(values["liquidity"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(values["liquidity"]["quoteAssetAddress"], BASE_USDT_ADDRESS)
        self.assertEqual(values["liquidity"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(values["liquidity"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["liquidity"]["uniswapPoolUrl"], OFFICIAL_UNISWAP_POOL_URL)
        self.assertEqual(values["liquidity"]["officialSwapUrl"], OFFICIAL_SWAP_URL)
        self.assertEqual(values["platformReadiness"]["geckoTerminal"]["status"], "approved")
        self.assertEqual(values["platformReadiness"]["geckoTerminal"]["approvalDate"], "2026-05-11")
        self.assertIn("prepared-but-weak-readiness", values["platformReadiness"]["coinGecko"]["status"])
        self.assertIn("prepared-but-weak-readiness", values["platformReadiness"]["coinMarketCap"]["status"])
        self.assertEqual(values["socialLinks"][0]["platform"], "Telegram")
        self.assertEqual(values["socialLinks"][0]["url"], TELEGRAM_URL)
        self.assertIn("third-party audited", values["doNotClaim"])
        self.assertIn("deferred by owner decision", values["longDescription"])

    def test_external_review_followup_tracker_is_actionable_and_conservative(self):
        tracker = (ROOT / "launch" / "external_review_followup_tracker.md").read_text()
        values = json.loads((ROOT / "launch" / "external_review_followup_tracker.json").read_text())

        self.assertIn("External Review Follow-Up Tracker", tracker)
        self.assertIn("Base Mainnet", tracker)
        self.assertIn("Chain ID: 8453", tracker)
        self.assertIn(MAINNET_ADDRESS, tracker)
        self.assertIn(VERIFY_PAGE_URL, tracker)
        self.assertIn(MARKET_PAGE_URL, tracker)
        self.assertIn(TELEGRAM_URL, tracker)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, tracker)
        self.assertIn("Submitted on 2026-05-09 and awaiting BaseScan review", tracker)
        self.assertIn("cxy070800@gmail.com", tracker)
        self.assertIn("False-positive report submitted on 2026-05-10", tracker)
        self.assertIn("warning removal not confirmed", tracker)
        self.assertIn("Token information update approved on 2026-05-11", tracker)
        self.assertIn("GCAgochina@outlook.com", tracker)
        self.assertIn("CoinGecko", tracker)
        self.assertIn("CoinMarketCap", tracker)
        self.assertIn("Not submitted", tracker)
        self.assertIn("No third-party audit has been completed", tracker)
        self.assertIn("BaseScan Follow-Up Template", tracker)
        self.assertIn("Blockaid Follow-Up Template", tracker)
        self.assertIn(SWAP_TEST_BUY_TX, tracker)
        self.assertIn(SWAP_TEST_SELL_TX, tracker)
        self.assertIn("Do not say the BaseScan token profile is approved", tracker)
        self.assertIn("Do not say the Blockaid / MetaMask warning has been removed", tracker)
        self.assertIn("self-trading, wash trading, or fake volume", tracker)

        self.assertEqual(values["documentStatus"], "prepared")
        self.assertEqual(values["canonicalIdentity"]["chainId"], 8453)
        self.assertEqual(values["canonicalIdentity"]["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(values["canonicalIdentity"]["verifyUrl"], VERIFY_PAGE_URL)
        self.assertEqual(values["canonicalIdentity"]["marketPageUrl"], MARKET_PAGE_URL)
        self.assertEqual(values["canonicalIdentity"]["telegramUrl"], TELEGRAM_URL)
        self.assertEqual(values["canonicalIdentity"]["officialPoolPair"], "GCA/USDT")
        self.assertEqual(values["canonicalIdentity"]["officialPoolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(values["canonicalIdentity"]["geckoTerminalPoolUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["platforms"]["baseScan"]["profileStatus"], "submitted-awaiting-review")
        self.assertEqual(values["platforms"]["baseScan"]["replyInbox"], "cxy070800@gmail.com")
        self.assertEqual(values["platforms"]["blockaid"]["reportStatus"], "submitted-warning-removal-not-confirmed")
        self.assertEqual(values["platforms"]["geckoTerminal"]["profileStatus"], "approved")
        self.assertEqual(values["platforms"]["geckoTerminal"]["approvalDate"], "2026-05-11")
        self.assertEqual(values["platforms"]["geckoTerminal"]["submissionEmail"], "GCAgochina@outlook.com")
        self.assertEqual(values["platforms"]["dexScreener"]["status"], "discoverable-through-gca-usdt-pool")
        self.assertEqual(values["platforms"]["coinGecko"]["status"], "not-submitted")
        self.assertEqual(values["platforms"]["coinMarketCap"]["status"], "not-submitted")
        self.assertEqual(values["platforms"]["thirdPartyAudit"]["status"], "deferred-after-quote-requests")
        self.assertFalse(values["coinGeckoCoinMarketCapGate"]["ready"])
        self.assertIn("wash trading", values["coinGeckoCoinMarketCapGate"]["requiredBeforeSubmission"][3])
        self.assertIn("No third-party audit has been completed.", values["safePublicClaims"])
        self.assertIn("deep liquidity or price backing", values["doNotClaim"])

    def test_geckoterminal_runbook_is_copyable_and_conservative(self):
        runbook = (ROOT / "launch" / "geckoterminal_update_runbook.md").read_text()
        values = json.loads((ROOT / "launch" / "geckoterminal_form_values.json").read_text())

        self.assertIn("approved on 2026-05-11", runbook)
        self.assertIn("Your request to update information for GCA has been approved", runbook)
        self.assertIn("Your form was submitted successfully", runbook)
        self.assertIn("Update Token Info", runbook)
        self.assertIn("launch/geckoterminal_form_values.json", runbook)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, runbook)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, runbook)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, runbook)
        self.assertIn(OFFICIAL_SWAP_URL, runbook)
        self.assertIn("GCA/USDT", runbook)
        self.assertIn("https://gcagochina.com/", runbook)
        self.assertIn("https://gcagochina.com/assets/gca-logo.svg", runbook)
        self.assertIn("https://gcagochina.com/whitepaper.html", runbook)
        self.assertIn("https://gcagochina.com/utility.html", runbook)
        self.assertIn("no completed third-party audit", runbook)
        self.assertIn("account is frozen", runbook)
        self.assertIn(TELEGRAM_URL, runbook)
        self.assertIn(MAINNET_ADDRESS, runbook)
        self.assertIn(RESERVE_WALLET, runbook)

        self.assertEqual(values["submissionStatus"], "approved")
        self.assertEqual(values["approvalDate"], "2026-05-11")
        self.assertEqual(values["reviewStatus"], "approved")
        self.assertEqual(values["platform"], "GeckoTerminal")
        self.assertEqual(values["chainId"], 8453)
        self.assertEqual(values["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(values["website"], "https://gcagochina.com/")
        self.assertEqual(values["logoUrl"], "https://gcagochina.com/assets/gca-logo.svg")
        self.assertEqual(values["logoPngUrl"], "https://gcagochina.com/assets/gca-logo.png")
        self.assertEqual(values["utilityThesisUrl"], "https://gcagochina.com/utility.html")
        self.assertEqual(values["officialEmail"], "GCAgochina@outlook.com")
        self.assertEqual(values["socialLinks"][0]["platform"], "Telegram")
        self.assertEqual(values["socialLinks"][0]["url"], TELEGRAM_URL)
        self.assertEqual(values["targetPoolUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["liquidity"]["dex"], "Uniswap v4")
        self.assertEqual(values["liquidity"]["pair"], "GCA/USDT")
        self.assertEqual(values["liquidity"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(values["liquidity"]["quoteAssetAddress"], BASE_USDT_ADDRESS)
        self.assertEqual(values["liquidity"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(values["liquidity"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["liquidity"]["uniswapPoolUrl"], OFFICIAL_UNISWAP_POOL_URL)
        self.assertEqual(values["liquidity"]["officialSwapUrl"], OFFICIAL_SWAP_URL)
        self.assertEqual(values["supplyDisclosure"]["ownerReserveWallet"], RESERVE_WALLET)
        self.assertIn("completed OTP verification", values["officialEmailUse"])

    def test_internal_security_review_is_not_third_party_audit(self):
        report = (ROOT / "audit" / "gca_internal_security_review.md").read_text()
        scope = (ROOT / "launch" / "audit_scope.md").read_text()
        plan = (ROOT / "audit" / "third_party_audit_plan.md").read_text()
        request = (ROOT / "audit" / "third_party_audit_request.md").read_text()
        package = json.loads((ROOT / "audit" / "third_party_audit_package.json").read_text())
        self.assertIn("not a third-party audit", report)
        self.assertIn("No third-party audit has been completed", scope)
        self.assertIn("must not say", scope)
        self.assertIn("No mint function exists", report)
        self.assertIn("No owner or admin role exists", report)
        self.assertIn(MAINNET_ADDRESS, report)
        self.assertIn("Third-party audit is not complete", plan)
        self.assertIn("Quote request", request)
        self.assertEqual(package["status"], "audit-deferred-after-quote-requests")
        self.assertFalse(package["publicClaimState"]["thirdPartyAuditCompleted"])
        self.assertEqual(package["ownerDecision"]["status"], "deferred")
        self.assertIn("not to commission or pay", package["ownerDecision"]["summary"])
        self.assertIn("No immediate audit action", package["nextRequiredOwnerAction"])
        self.assertIn("Do not approve payment", package["nextRequiredOwnerAction"])
        self.assertEqual(
            [entry["name"] for entry in package["submissionLog"]],
            ["QuillAudits", "Hacken", "OpenZeppelin"],
        )
        self.assertTrue(all(entry["status"] == "submitted" for entry in package["submissionLog"]))
        self.assertIn("69ff764fef9d6e0aa30257f6", package["submissionLog"][0]["evidence"])
        self.assertIn("We've received your request", package["submissionLog"][1]["evidence"])
        self.assertIn("9b09cc7a-a53b-44b9-9763-98ac7e482434", package["submissionLog"][2]["evidence"])

    def test_swap_test_evidence_is_conservative(self):
        evidence = (ROOT / "launch" / "swap_test_evidence.md").read_text()
        self.assertIn("Functional Swap Test Evidence", evidence)
        self.assertIn("Current Official Market Route", evidence)
        self.assertIn("GCA/USDT", evidence)
        self.assertIn(OFFICIAL_POOL_ADDRESS, evidence)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, evidence)
        self.assertIn("historical functional evidence only", evidence.lower())
        self.assertIn("GCA/WETH", evidence)
        self.assertIn("0x79fc0b367adbd79118c664f5ee27eb6ff8cb69ff", evidence)
        self.assertIn(MAINNET_ADDRESS, evidence)
        self.assertIn(SWAP_TEST_BUY_TX, evidence)
        self.assertIn(SWAP_TEST_SELL_TX, evidence)
        self.assertIn("both buy and sell swaps", evidence)
        self.assertIn("not proof of organic demand", evidence)
        self.assertIn("Risk warning removed", evidence)
        self.assertIn("Deep liquidity", evidence)

    def test_blockaid_false_positive_report_records_submission(self):
        report = (ROOT / "launch" / "blockaid_false_positive_report.md").read_text()
        self.assertIn("Submitted on 2026-05-10", report)
        self.assertIn("https://report.blockaid.io/mistake", report)
        self.assertIn("https://report.blockaid.io/submittionSuccessfully", report)
        self.assertIn("Report Sent", report)
        self.assertIn("Thank you for reporting", report)
        self.assertIn(MAINNET_ADDRESS, report)
        self.assertIn(SWAP_TEST_BUY_TX, report)
        self.assertIn(SWAP_TEST_SELL_TX, report)
        self.assertIn("not a claim that the warning has been removed", report)
        self.assertIn("Current Follow-Up Context", report)
        self.assertIn("Current Follow-Up Message Template", report)
        self.assertIn("GCA/USDT", report)
        self.assertIn(OFFICIAL_POOL_ADDRESS, report)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, report)

    def test_site_has_whitepaper_page(self):
        index = (ROOT / "site" / "index.html").read_text()
        whitepaper = (ROOT / "site" / "whitepaper.html").read_text()
        self.assertIn('href="whitepaper.html"', index)
        self.assertIn("GCA Whitepaper", whitepaper)
        self.assertIn("Version 0.5", whitepaper)
        self.assertIn("Go China Access", index)
        self.assertIn("Go China Access", whitepaper)
        self.assertIn("planned access to non-custodial quant risk tools", whitepaper)
        self.assertIn("ENTRY_READY signal review", whitepaper)
        self.assertIn("one wallet holding at least 10,000 GCA", whitepaper)
        self.assertIn("100 Web3 Radar utility credits", whitepaper)
        self.assertIn("one wallet holding at least 1,000,000 GCA", whitepaper)
        self.assertIn("GCA Member status", whitepaper)
        self.assertIn("higher utility credit limits", whitepaper)
        self.assertIn("not a token rebate", whitepaper)
        self.assertIn("Verified Utility Boundaries", whitepaper)
        self.assertIn("deployer-wallet ownership verification are complete", whitepaper)
        self.assertIn("Owner-held reserve", whitepaper)
        self.assertIn("600,000,000 GCA", whitepaper)
        self.assertIn(RESERVE_WALLET, whitepaper)
        self.assertIn(RESERVE_TX, whitepaper)
        self.assertIn(SECOND_RESERVE_TX, whitepaper)
        self.assertIn("not a lock, vesting contract, or Safe multisig", whitepaper)
        self.assertIn("mailto:GCAgochina@outlook.com", whitepaper)
        self.assertIn("https://gcagochina.com/buy.html", whitepaper)
        self.assertIn("https://gcagochina.com/utility.html", whitepaper)
        self.assertIn(TELEGRAM_URL, whitepaper)
        self.assertIn("starter liquidity only", whitepaper)
        self.assertIn("Third-party audit quote requests were submitted to QuillAudits, Hacken, and OpenZeppelin on 2026-05-10", whitepaper)
        self.assertIn("then deferred by owner decision", whitepaper)
        self.assertIn("GCA/USDT", whitepaper)
        self.assertIn(OFFICIAL_POOL_ADDRESS, whitepaper)
        self.assertIn(BASE_USDT_ADDRESS, whitepaper)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, whitepaper)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, whitepaper)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, whitepaper)
        self.assertIn("GeckoTerminal token information was approved on 2026-05-11", whitepaper)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, whitepaper)
        self.assertIn(MAINNET_ADDRESS, whitepaper)

    def test_telegram_pinned_buy_announcement_is_safe_to_post(self):
        pin = (ROOT / "launch" / "telegram_pinned_buy_announcement.md").read_text()
        self.assertIn("Buy guide", pin)
        self.assertIn("Verify official links", pin)
        self.assertIn(VERIFY_PAGE_URL, pin)
        self.assertIn("https://gcagochina.com/buy.html", pin)
        self.assertIn("Uniswap swap", pin)
        self.assertIn(OFFICIAL_SWAP_URL, pin)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, pin)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, pin)
        self.assertIn("Official GCA/USDT pool", pin)
        self.assertIn(MAINNET_ADDRESS, pin)
        self.assertIn("GCA is on Base Mainnet only", pin)
        self.assertIn("No third-party audit has been completed", pin)
        self.assertIn("starter-depth only", pin)
        self.assertIn("If MetaMask or Uniswap shows a warning", pin)
        self.assertIn("use the verify page to confirm the contract, pool, official links, and risks", pin)
        self.assertIn("Do not add price targets", pin)
        self.assertIn("Do not say the Blockaid / MetaMask warning has been removed", pin)


if __name__ == "__main__":
    unittest.main()
