import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAINNET_ADDRESS = "0x3197c42f4a06f7be32a9a742ac2a766f0ff682c6"
RESERVE_WALLET = "0x5e8F84748612B913aAcC937492AC25dc5630E246"
RESERVE_TX = "0x4c342e1f4c969d0a73018637b778d5a76bd05f54749ff1fd2d19327fd5c01c67"
SECOND_RESERVE_TX = "0xfffb674448abdbd3af45bb0a30c48e5fbb0e675542b971f031381254b5dc5317"
TELEGRAM_URL = "https://t.me/gcagochinaofficial"
SWAP_TEST_BUY_TX = "0xf79e52ea56a299a30c2d297be99c970295864ed262c01fdcb7e3f60ca669b040"
SWAP_TEST_SELL_TX = "0x0ff618062abc6e28933699d4e3bd723026f8505e4a0155db3068073b6fdc86e7"
OFFICIAL_POOL_ADDRESS = "0xfe6a598bf738d7eec9640897064ca3a490128d3d447ced96077aef8e9dd1c1d0"
BASE_USDT_ADDRESS = "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
OFFICIAL_DEXSCREENER_URL = f"https://dexscreener.com/base/{OFFICIAL_POOL_ADDRESS}"
OFFICIAL_GECKOTERMINAL_URL = f"https://www.geckoterminal.com/base/pools/{OFFICIAL_POOL_ADDRESS}"
OFFICIAL_UNISWAP_POOL_URL = f"https://app.uniswap.org/explore/pools/base/{OFFICIAL_POOL_ADDRESS}"
OFFICIAL_SWAP_URL = (
    f"https://app.uniswap.org/swap?chain=base&inputCurrency={BASE_USDT_ADDRESS}"
    f"&outputCurrency={MAINNET_ADDRESS}"
)
OFFICIAL_SWAP_URL_HTML = OFFICIAL_SWAP_URL.replace("&", "&amp;")
OLD_WETH_POOL_ADDRESS = "0x79fc0b367adbd79118c664f5ee27eb6ff8cb69ff"


class LaunchPackageTests(unittest.TestCase):
    def test_logo_matches_basescan_size_target(self):
        logo = (ROOT / "brand" / "gca-logo.svg").read_text()
        self.assertIn('width="32"', logo)
        self.assertIn('height="32"', logo)
        self.assertIn("GCA token logo", logo)
        self.assertTrue((ROOT / "brand" / "gca-logo.png").exists())
        self.assertTrue((ROOT / "site" / "assets" / "gca-logo.png").exists())

    def test_public_site_uses_mainnet_identity(self):
        site = (ROOT / "site" / "index.html").read_text()
        buy = (ROOT / "site" / "buy.html").read_text()
        status = (ROOT / "site" / "status.html").read_text()
        listing = (ROOT / "site" / "listing-kit.html").read_text()
        project = json.loads((ROOT / "site" / "project.json").read_text())
        utility = (ROOT / "site" / "utility.html").read_text()
        members = (ROOT / "site" / "members.html").read_text()
        self.assertIn("Base Mainnet", site)
        self.assertIn("chainId 8453", site)
        self.assertIn(MAINNET_ADDRESS, site)
        self.assertIn(MAINNET_ADDRESS, buy)
        self.assertIn(MAINNET_ADDRESS, status)
        self.assertIn(MAINNET_ADDRESS, listing)
        self.assertEqual(project["contractAddress"], MAINNET_ADDRESS)
        self.assertIn(MAINNET_ADDRESS, utility)
        self.assertIn(MAINNET_ADDRESS, members)
        self.assertIn("Base Mainnet", members)
        self.assertIn("Base Mainnet", buy)
        self.assertIn("chainId 8453", buy)
        self.assertIn("https://basescan.org/address/", site)
        self.assertNotIn("sepolia.basescan.org", site)
        self.assertNotIn("sepolia.basescan.org", buy)
        self.assertNotIn("sepolia.basescan.org", status)
        self.assertNotIn("sepolia.basescan.org", listing)

    def test_public_site_sets_custom_domain(self):
        cname = (ROOT / "site" / "CNAME").read_text().strip()
        self.assertEqual(cname, "gcagochina.com")

    def test_site_has_discovery_files(self):
        robots = (ROOT / "site" / "robots.txt").read_text()
        sitemap = (ROOT / "site" / "sitemap.xml").read_text()

        self.assertIn("User-agent: *", robots)
        self.assertIn("Allow: /", robots)
        self.assertIn("Sitemap: https://gcagochina.com/sitemap.xml", robots)
        self.assertIn("https://gcagochina.com/", sitemap)
        self.assertIn("https://gcagochina.com/status.html", sitemap)
        self.assertIn("https://gcagochina.com/listing-kit.html", sitemap)
        self.assertIn("https://gcagochina.com/project.json", sitemap)
        self.assertIn("https://gcagochina.com/tokenlist.json", sitemap)
        self.assertIn("https://gcagochina.com/buy.html", sitemap)
        self.assertIn("https://gcagochina.com/whitepaper.html", sitemap)

    def test_public_site_discloses_current_operational_status(self):
        site = (ROOT / "site" / "index.html").read_text()
        self.assertIn("BaseScan token profile update has been submitted", site)
        self.assertIn('href="buy.html"', site)
        self.assertIn('href="status.html"', site)
        self.assertIn('href="listing-kit.html"', site)
        self.assertIn("Go China Access", site)
        self.assertIn("Go China AI Quant Access", site)
        self.assertIn("Go China macro narrative", site)
        self.assertIn("Web3 Radar-style quant research", site)
        self.assertIn("planned access path for liquidation replay, backtesting, risk alerts, ENTRY_READY review, and position sizing", site)
        self.assertIn("local verified-access backend", site)
        self.assertIn("Verified Utility: Web3 Radar Access Layer", site)
        self.assertIn("Access Bridge Pipeline", site)
        self.assertIn("Users submit email, Telegram, Base wallet, declared GCA balance, and program intent", site)
        self.assertIn("verified balances create service-access ledger records only", site)
        self.assertIn("each registered user may verify one wallet holding at least 10,000 GCA", site)
        self.assertIn("one-time 100 Web3 Radar utility credits ledger record", site)
        self.assertIn("one wallet holding at least 1,000,000 GCA", site)
        self.assertIn("GCA Member status", site)
        self.assertIn("not cash, tokens, income, reimbursement, or trading permission", site)
        self.assertIn("400,000,000 GCA / 40%", site)
        self.assertIn("600,000,000 GCA / 60%", site)
        self.assertIn("exact circulating supply should still be verified", site)
        self.assertIn(RESERVE_WALLET, site)
        self.assertIn(RESERVE_TX, site)
        self.assertIn(SECOND_RESERVE_TX, site)
        self.assertIn("mailto:GCAgochina@outlook.com", site)
        self.assertIn(TELEGRAM_URL, site)
        self.assertIn("Project contact email", site)
        self.assertNotIn("https://x.com/GCAgochina", site)
        self.assertNotIn("Official X profile", site)
        self.assertIn("No third-party audit has been completed", site)
        self.assertIn("Security &amp; Transparency", site)
        self.assertIn("Third-party audit quote requests were submitted to QuillAudits, Hacken, and OpenZeppelin on 2026-05-10", site)
        self.assertIn("then deferred by owner decision", site)
        self.assertIn("no post-deployment mint function", site)
        self.assertIn("no owner/admin role", site)
        self.assertIn("no owner/admin role, proxy or upgrade path, pause switch, blacklist, transfer tax, hidden fee, custody, or withdrawal path", site)
        self.assertIn("pool is shallow", site)
        self.assertIn("high price impact and slippage", site)
        self.assertIn(OFFICIAL_POOL_ADDRESS, site)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, site)
        self.assertIn("Market References", site)
        self.assertIn("GCA/USDT", site)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, site)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, site)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, site)
        self.assertIn("GeckoTerminal token information was approved on 2026-05-11", site)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, site)
        self.assertIn("starter liquidity only", site)

    def test_members_page_supports_local_pre_registration_safely(self):
        members = (ROOT / "site" / "members.html").read_text()
        self.assertIn("GCA Member Pre-Registration", members)
        self.assertIn("This page creates a local pre-registration packet", members)
        self.assertIn("does not create a live Web3 Radar account", members)
        self.assertIn("10,000 GCA", members)
        self.assertIn("100 Web3 Radar utility credits", members)
        self.assertIn("1,000,000 GCA", members)
        self.assertIn("GCA Member", members)
        self.assertIn("Connect Wallet", members)
        self.assertIn("Generate Packet", members)
        self.assertIn("Submit Packet", members)
        self.assertIn("Copy Packet", members)
        self.assertIn("Download JSON", members)
        self.assertIn("Email Packet", members)
        self.assertIn('const SUBMISSION_ENDPOINT = "";', members)
        self.assertIn('const REVIEWED_WEB3_RADAR_ENDPOINT_PATH = "/gca/pre-registrations";', members)
        self.assertIn('const WALLET_VERIFICATION_ENDPOINT_PATH = "/gca/wallet-verifications";', members)
        self.assertIn('const CREDIT_LEDGER_ENDPOINT_PATH = "/gca/credit-ledger";', members)
        self.assertIn('const MEMBER_LEDGER_ENDPOINT_PATH = "/gca/member-ledger";', members)
        self.assertIn("fetch(SUBMISSION_ENDPOINT", members)
        self.assertIn("Direct submission is not connected", members)
        self.assertIn("/gca/wallet-verifications", members)
        self.assertIn("/gca/credit-ledger", members)
        self.assertIn("/gca/member-ledger", members)
        self.assertIn("/gca/member-review", members)
        self.assertIn("Current public submission mode", members)
        self.assertIn("local-only-pre-registration-backend-verification-ready-public-claim-not-connected", members)
        self.assertIn("No private key, seed phrase, exchange API secret, withdrawal permission, or custody request", members)
        self.assertIn("No cash, token rebate, income, reimbursement, trading permission, or risk-control bypass", members)
        self.assertIn("walletAddressFormatOk", members)
        self.assertIn("eth_requestAccounts", members)
        self.assertIn("GCAgochina@outlook.com", members)

    def test_utility_page_connects_gca_to_quant_tools_safely(self):
        utility = (ROOT / "site" / "utility.html").read_text()
        self.assertIn("GCA Utility Thesis", utility)
        self.assertIn("Go China macro-narrative token", utility)
        self.assertIn("Web3 Radar-style non-custodial quant tools", utility)
        self.assertIn("liquidation replay reports", utility)
        self.assertIn("risk-warning credits", utility)
        self.assertIn("realistic backtests", utility)
        self.assertIn("ENTRY_READY signal review", utility)
        self.assertIn("Position calculator", utility)
        self.assertIn("risk-control training", utility)
        self.assertIn("GCA Member status", utility)
        self.assertIn("Verified Holder Programs", utility)
        self.assertIn("one wallet holding at least 10,000 GCA", utility)
        self.assertIn("one-time 100 Web3 Radar utility credits ledger record", utility)
        self.assertIn("one wallet holding at least 1,000,000 GCA", utility)
        self.assertIn("higher utility credit limits", utility)
        self.assertIn("not token rebates", utility)
        self.assertIn("Platform revenue distribution", utility)
        self.assertIn("Token ownership bypassing risk controls", utility)
        self.assertIn("verified utility backend path", utility)
        self.assertIn("does not represent custody, redemption rights", utility)
        self.assertIn("return guarantees", utility)

    def test_buy_page_is_official_and_conservative(self):
        buy = (ROOT / "site" / "buy.html").read_text()
        self.assertIn("Buy GCA", buy)
        self.assertIn("Open Uniswap Swap", buy)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, buy)
        self.assertIn(MAINNET_ADDRESS, buy)
        self.assertIn(BASE_USDT_ADDRESS, buy)
        self.assertIn("Base Mainnet", buy)
        self.assertIn("Chain ID", buy)
        self.assertIn("8453", buy)
        self.assertIn("MetaMask Import", buy)
        self.assertIn("Add to MetaMask", buy)
        self.assertIn("GeckoTerminal pool", buy)
        self.assertIn("GCA/USDT", buy)
        self.assertIn("GCA/USDT approved", buy)
        self.assertIn(OFFICIAL_POOL_ADDRESS, buy)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, buy)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, buy)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, buy)
        self.assertIn("A Blockaid / MetaMask false-positive report was submitted on 2026-05-10", buy)
        self.assertIn("does not mean wallet warnings have been removed", buy)
        self.assertIn("no third-party audit has been completed", buy)
        self.assertIn("This is not investment advice", buy)
        self.assertIn("does not guarantee price, liquidity, execution, or safety", buy)
        self.assertIn("If a wallet or DEX warning appears, stop and verify", buy)

    def test_status_page_centralizes_public_verification(self):
        status = (ROOT / "site" / "status.html").read_text()
        index = (ROOT / "site" / "index.html").read_text()
        buy = (ROOT / "site" / "buy.html").read_text()
        members = (ROOT / "site" / "members.html").read_text()
        utility = (ROOT / "site" / "utility.html").read_text()
        whitepaper = (ROOT / "site" / "whitepaper.html").read_text()

        self.assertIn("GCA Project Status", status)
        self.assertIn("Base Mainnet / chainId 8453", status)
        self.assertIn(MAINNET_ADDRESS, status)
        self.assertIn(OFFICIAL_POOL_ADDRESS, status)
        self.assertIn(BASE_USDT_ADDRESS, status)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, status)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, status)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, status)
        self.assertIn("Approved 2026-05-11", status)
        self.assertIn("Submitted, awaiting review", status)
        self.assertIn("BaseScan public token profile publication", status)
        self.assertIn("Wallet warning removal after Blockaid report", status)
        self.assertIn("CoinGecko tracked listing", status)
        self.assertIn("CoinMarketCap tracked listing", status)
        self.assertIn("No third-party audit has been completed", status)
        self.assertIn("600,000,000 GCA", status)
        self.assertIn("normal owner-controlled wallet", status)
        self.assertIn("Do not say the BaseScan token profile is approved", status)
        self.assertIn("Do not say GCA is externally audited", status)
        self.assertIn("Do not describe liquidity as deep", status)
        self.assertIn("Do not claim price support", status)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, status)

        for page in (index, buy, members, utility, whitepaper):
            self.assertIn('href="status.html"', page)
            self.assertIn('href="listing-kit.html"', page)

    def test_listing_kit_and_project_json_are_copyable(self):
        kit = (ROOT / "site" / "listing-kit.html").read_text()
        project = json.loads((ROOT / "site" / "project.json").read_text())

        self.assertIn("GCA Listing Kit", kit)
        self.assertIn("Machine-Readable JSON", kit)
        self.assertIn("project.json", kit)
        self.assertIn("Token List JSON", kit)
        self.assertIn("tokenlist.json", kit)
        self.assertIn("Token name", kit)
        self.assertIn("GCA / Go China Access", kit)
        self.assertIn(MAINNET_ADDRESS, kit)
        self.assertIn(OFFICIAL_POOL_ADDRESS, kit)
        self.assertIn(BASE_USDT_ADDRESS, kit)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, kit)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, kit)
        self.assertIn(OFFICIAL_SWAP_URL_HTML, kit)
        self.assertIn("Short Description", kit)
        self.assertIn("Long Description", kit)
        self.assertIn("BaseScan", kit)
        self.assertIn("submitted and awaiting review", kit)
        self.assertIn("GeckoTerminal", kit)
        self.assertIn("approved on 2026-05-11", kit)
        self.assertIn("CoinGecko / CMC", kit)
        self.assertIn("not submitted", kit)
        self.assertIn("Do Not Claim", kit)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, kit)

        self.assertEqual(project["projectName"], "GCA")
        self.assertEqual(project["network"], "Base Mainnet")
        self.assertEqual(project["chainId"], 8453)
        self.assertEqual(project["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(project["listingKitUrl"], "https://gcagochina.com/listing-kit.html")
        self.assertEqual(project["tokenListUrl"], "https://gcagochina.com/tokenlist.json")
        self.assertEqual(project["market"]["officialPair"], "GCA/USDT")
        self.assertEqual(project["market"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(project["market"]["quoteAssetAddress"], BASE_USDT_ADDRESS)
        self.assertEqual(project["market"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(project["market"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(project["market"]["officialSwapUrl"], OFFICIAL_SWAP_URL)
        self.assertEqual(project["supplyDisclosure"]["ownerReserveWallet"], RESERVE_WALLET)
        self.assertEqual(project["platformStatus"]["baseScanTokenProfile"], "submitted-awaiting-review")
        self.assertEqual(project["platformStatus"]["geckoTerminalTokenInfo"], "approved-2026-05-11")
        self.assertEqual(project["platformStatus"]["thirdPartyAudit"], "not-completed")

    def test_token_list_json_is_official_and_conservative(self):
        tokenlist = json.loads((ROOT / "site" / "tokenlist.json").read_text())
        self.assertEqual(tokenlist["name"], "GCA Official Token List")
        self.assertEqual(tokenlist["version"], {"major": 1, "minor": 0, "patch": 0})
        self.assertIn("base", tokenlist["keywords"])
        self.assertEqual(len(tokenlist["tokens"]), 1)

        token = tokenlist["tokens"][0]
        self.assertEqual(token["chainId"], 8453)
        self.assertEqual(token["address"], MAINNET_ADDRESS)
        self.assertEqual(token["name"], "GCA")
        self.assertEqual(token["symbol"], "GCA")
        self.assertEqual(token["decimals"], 18)
        self.assertEqual(token["logoURI"], "https://gcagochina.com/assets/gca-logo.png")

        extensions = token["extensions"]
        self.assertEqual(extensions["website"], "https://gcagochina.com/")
        self.assertEqual(extensions["statusPage"], "https://gcagochina.com/status.html")
        self.assertEqual(extensions["listingKit"], "https://gcagochina.com/listing-kit.html")
        self.assertEqual(extensions["projectJson"], "https://gcagochina.com/project.json")
        self.assertEqual(extensions["officialTelegram"], TELEGRAM_URL)
        self.assertEqual(extensions["geckoTerminal"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(extensions["dexScreener"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(extensions["officialSwap"], OFFICIAL_SWAP_URL)
        self.assertEqual(extensions["officialPair"], "GCA/USDT")
        self.assertEqual(extensions["officialPool"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(extensions["geckoTerminalStatus"], "approved-2026-05-11")
        self.assertEqual(extensions["baseScanTokenProfileStatus"], "submitted-awaiting-review")
        self.assertEqual(extensions["thirdPartyAuditStatus"], "not-completed")
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, json.dumps(tokenlist))

    def test_public_materials_avoid_investment_promises(self):
        paths = [
            ROOT / "site" / "index.html",
            ROOT / "site" / "buy.html",
            ROOT / "site" / "status.html",
            ROOT / "site" / "listing-kit.html",
            ROOT / "site" / "members.html",
            ROOT / "site" / "utility.html",
            ROOT / "docs" / "whitepaper.md",
            ROOT / "docs" / "mainnet_public_profile.md",
            ROOT / "launch" / "basescan_token_submission.md",
            ROOT / "launch" / "basescan_review_followup.md",
            ROOT / "launch" / "token_allocation_plan.md",
            ROOT / "launch" / "liquidity_pool_runbook.md",
            ROOT / "launch" / "launch_status.md",
            ROOT / "launch" / "data_platform_package.md",
            ROOT / "launch" / "geckoterminal_update_runbook.md",
            ROOT / "launch" / "member_pre_registration_runbook.md",
            ROOT / "launch" / "telegram_channel_runbook.md",
            ROOT / "launch" / "telegram_pinned_buy_announcement.md",
        ]
        forbidden = re.compile(r"\b(guaranteed returns?|profit sharing|risk[- ]?free|稳赚|保本|拉盘|炒币)\b", re.I)
        for path in paths:
            with self.subTest(path=path.name):
                self.assertIsNone(forbidden.search(path.read_text()))

    def test_basescan_submission_has_required_public_placeholders(self):
        submission = (ROOT / "launch" / "basescan_token_submission.md").read_text()
        self.assertIn("https://gcagochina.com/", submission)
        self.assertIn("Official contact email", submission)
        self.assertIn("cxy070800@gmail.com", submission)
        self.assertIn(TELEGRAM_URL, submission)
        self.assertIn("Gmail address", submission)
        self.assertIn("Submitted from the owner's browser session on 2026-05-09", submission)
        self.assertIn("deployer-wallet ownership verification were included", submission)
        self.assertIn("publicly listed on the official website", submission)
        self.assertIn("Public logo download URL", submission)
        self.assertNotIn("https://x.com/GCAgochina", submission)
        self.assertIn("https://basescan.org/tokenupdate/", submission)
        self.assertIn(MAINNET_ADDRESS, submission)

    def test_basescan_review_followup_is_actionable(self):
        followup = (ROOT / "launch" / "basescan_review_followup.md").read_text()
        self.assertIn("awaiting BaseScan review", followup)
        self.assertIn("cxy070800@gmail.com", followup)
        self.assertIn("Base Mainnet", followup)
        self.assertIn("Chain ID: 8453", followup)
        self.assertIn(MAINNET_ADDRESS, followup)
        self.assertIn("If BaseScan Approves", followup)
        self.assertIn("If BaseScan Requests Changes", followup)
        self.assertIn("Reply Template", followup)
        self.assertIn("Do not describe the BaseScan token profile as complete", followup)
        self.assertIn("https://gcagochina.com/status.html", followup)
        self.assertIn("Official GCA/USDT pool", followup)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, followup)

    def test_basescan_form_values_are_copyable(self):
        values = json.loads((ROOT / "launch" / "basescan_form_values.json").read_text())
        self.assertEqual(values["network"], "Base Mainnet")
        self.assertEqual(values["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(values["website"], "https://gcagochina.com/")
        self.assertEqual(values["utilityThesisUrl"], "https://gcagochina.com/utility.html")
        self.assertEqual(values["logoUrl"], "https://gcagochina.com/assets/gca-logo.svg")
        self.assertEqual(values["whitepaperUrl"], "https://gcagochina.com/whitepaper.html")
        self.assertEqual(values["officialEmail"], "cxy070800@gmail.com")
        self.assertIn("Gmail address", values["officialEmailNote"])
        self.assertEqual(values["targetPublicAllocation"], "400000000")
        self.assertEqual(values["targetPublicAllocationPercent"], 40)
        self.assertEqual(values["ownerHeldReserve"], "600000000")
        self.assertEqual(values["ownerHeldReservePercent"], 60)
        self.assertEqual(values["ownerReserveWallet"], RESERVE_WALLET)
        self.assertEqual(values["ownerReserveTransferTxs"], [RESERVE_TX, SECOND_RESERVE_TX])
        self.assertIn("normal owner-controlled wallet", values["ownerReserveCustodyNote"])
        self.assertIn("Go China Access", values["description"])
        self.assertIn("Go China macro narrative", values["description"])
        self.assertIn("non-custodial quant risk tools", values["description"])
        self.assertIn("ENTRY_READY signal review", values["description"])
        self.assertEqual(values["submissionStatus"], "submitted")
        self.assertEqual(values["reviewStatus"], "awaiting BaseScan review")
        self.assertEqual(values["socialLinks"][0]["platform"], "Telegram")
        self.assertEqual(values["socialLinks"][0]["url"], TELEGRAM_URL)
        self.assertIn("after the initial BaseScan submission", values["socialLinkNote"])
        self.assertEqual(values["officialMarketPool"]["pair"], "GCA/USDT")
        self.assertEqual(values["officialMarketPool"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(values["officialMarketPool"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["officialMarketPool"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(values["officialMarketPool"]["officialSwapUrl"], OFFICIAL_SWAP_URL)

    def test_token_allocation_plan_records_owner_reserve(self):
        plan = json.loads((ROOT / "launch" / "token_allocation_plan.json").read_text())
        doc = (ROOT / "launch" / "token_allocation_plan.md").read_text()
        self.assertEqual(plan["totalSupply"], "1000000000")
        self.assertEqual(plan["allocationPlanStatus"], "owner-reserve-increased")
        self.assertEqual(plan["allocations"][0]["amount"], "400000000")
        self.assertEqual(plan["allocations"][0]["percent"], 40)
        self.assertEqual(plan["allocations"][1]["amount"], "600000000")
        self.assertEqual(plan["allocations"][1]["percent"], 60)
        self.assertEqual(plan["allocations"][1]["holder"], RESERVE_WALLET)
        self.assertEqual(plan["allocations"][1]["transferTransactionHashes"], [RESERVE_TX, SECOND_RESERVE_TX])
        self.assertEqual(plan["ownerReserveWalletBalanceGca"], "600000000")
        self.assertEqual(plan["executedOwnerReserveTransfers"][1]["to"], RESERVE_WALLET)
        self.assertEqual(plan["executedOwnerReserveTransfers"][1]["transactionHash"], SECOND_RESERVE_TX)
        self.assertIn("owner/founder", plan["allocations"][1]["notes"])
        self.assertIn("target allocation", doc)
        self.assertIn("600,000,000 GCA", doc)
        self.assertIn("not be described as circulating", doc)
        self.assertIn("not a lock, vesting contract, or Safe multisig", doc)
        self.assertIn(RESERVE_WALLET, doc)
        self.assertIn(RESERVE_TX, doc)
        self.assertIn(SECOND_RESERVE_TX, doc)
        self.assertIn(MAINNET_ADDRESS, doc)
        self.assertEqual(plan["officialMarketPool"]["pair"], "GCA/USDT")
        self.assertEqual(plan["officialMarketPool"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, doc)

    def test_public_materials_do_not_overstate_basescan_review(self):
        paths = [
            ROOT / "site" / "index.html",
            ROOT / "site" / "buy.html",
            ROOT / "site" / "status.html",
            ROOT / "site" / "listing-kit.html",
            ROOT / "site" / "whitepaper.html",
            ROOT / "site" / "utility.html",
            ROOT / "docs" / "whitepaper.md",
            ROOT / "docs" / "mainnet_public_profile.md",
            ROOT / "launch" / "launch_status.md",
        ]
        forbidden = [
            "BaseScan profile complete",
            "BaseScan approved",
            "BaseScan token profile is complete",
            "BaseScan token profile has been accepted",
            "BaseScan token profile is live",
        ]
        for path in paths:
            text = path.read_text()
            with self.subTest(path=path.name):
                for phrase in forbidden:
                    self.assertNotIn(phrase, text)

    def test_liquidity_runbook_records_execution(self):
        runbook = (ROOT / "launch" / "liquidity_pool_runbook.md").read_text()
        self.assertIn("Executed on Base Mainnet.", runbook)
        self.assertIn("5087977", runbook)
        self.assertIn("0xef94e020c8b431151b789ca3e96c45ab0c18d20d15bf8d7d543630f1370fc158", runbook)
        self.assertIn(MAINNET_ADDRESS, runbook)

    def test_liquidity_plan_has_selected_mainnet_defaults(self):
        plan = json.loads((ROOT / "launch" / "liquidity_plan.json").read_text())
        self.assertEqual(plan["status"], "executed")
        self.assertEqual(plan["network"], "Base Mainnet")
        self.assertEqual(plan["chainId"], 8453)
        self.assertEqual(plan["protocolVersion"], "v3")
        self.assertEqual(plan["feeTier"], "1%")
        self.assertEqual(plan["selectedPlan"]["gcaAmount"], "100000")
        self.assertEqual(plan["selectedPlan"]["ethAmount"], "0.001")
        self.assertEqual(plan["selectedPlan"]["impliedFullyDilutedValueEth"], "10")
        self.assertEqual(plan["pair"]["baseToken"]["address"], MAINNET_ADDRESS)
        self.assertEqual(plan["execution"]["positionTokenId"], "5087977")
        self.assertEqual(plan["execution"]["poolAddress"], "0x79fc0b367adbd79118c664f5ee27eb6ff8cb69ff")

    def test_liquidity_deployment_record_is_on_base_mainnet(self):
        record = json.loads((ROOT / "deployments" / "base-mainnet-gca-liquidity.json").read_text())
        self.assertEqual(record["status"], "executed")
        self.assertEqual(record["network"], "Base Mainnet")
        self.assertEqual(record["chainId"], 8453)
        self.assertEqual(record["tokenId"], "5087977")
        self.assertEqual(record["transactionHash"], "0xef94e020c8b431151b789ca3e96c45ab0c18d20d15bf8d7d543630f1370fc158")
        self.assertEqual(record["tokens"]["token0"]["address"], MAINNET_ADDRESS)
        self.assertEqual(record["tokens"]["token1"]["symbol"], "WETH")
        self.assertEqual(record["position"]["tickLower"], -887200)
        self.assertEqual(record["position"]["tickUpper"], 887200)

    def test_launch_status_separates_done_from_external_blockers(self):
        status = (ROOT / "launch" / "launch_status.md").read_text()
        self.assertIn("## Done", status)
        self.assertIn("## Needs Owner Input Or External Service", status)
        self.assertIn("https://gcagochina.com/", status)
        self.assertIn("DNS records for `gcagochina.com`", status)
        self.assertIn("GitHub Pages HTTPS certificate issued", status)
        self.assertIn("Data platform submission package prepared", status)
        self.assertIn("GeckoTerminal token info update runbook prepared", status)
        self.assertIn("GeckoTerminal token info update submitted on 2026-05-09", status)
        self.assertIn("GeckoTerminal token information update approved on 2026-05-11", status)
        self.assertIn("Public project status page prepared", status)
        self.assertIn("Public listing kit and machine-readable project JSON prepared", status)
        self.assertIn("Official token list JSON prepared", status)
        self.assertNotIn("Wait for GeckoTerminal review", status)
        self.assertIn(TELEGRAM_URL, status)
        self.assertIn("Telegram channel runbook prepared", status)
        self.assertIn("First official Telegram announcement pinned on 2026-05-10", status)
        self.assertIn("Official buy guide page prepared", status)
        self.assertIn("https://gcagochina.com/buy.html", status)
        self.assertIn("Telegram replacement pinned buy announcement template prepared", status)
        self.assertIn("launch/telegram_pinned_buy_announcement.md", status)
        self.assertIn("Replace the Telegram pinned message", status)
        self.assertIn("buy/sell functional swap tests observed on 2026-05-10", status)
        self.assertIn("launch/swap_test_evidence.md", status)
        self.assertIn("Blockaid false-positive report submitted on 2026-05-10", status)
        self.assertIn("does not mean the warning has been removed", status)
        self.assertIn("must not be described as proof of organic volume", status)
        self.assertIn("Third-party audit quote requests submitted to QuillAudits, Hacken, and OpenZeppelin on 2026-05-10", status)
        self.assertIn("Owner decided on 2026-05-10 to defer third-party audit", status)
        self.assertIn("Archive any audit quote replies", status)
        self.assertIn("quote submission is not an audit", status)
        self.assertNotIn("Pin the first Telegram announcement manually", status)
        self.assertNotIn("wait for GitHub Pages HTTPS to become active", status)
        self.assertIn("Base Mainnet / chainId 8453", status)
        self.assertIn("Base Sepolia / chainId 84532", status)
        self.assertIn(RESERVE_WALLET, status)
        self.assertIn(RESERVE_TX, status)
        self.assertIn(SECOND_RESERVE_TX, status)

    def test_telegram_channel_runbook_records_official_channel(self):
        runbook = (ROOT / "launch" / "telegram_channel_runbook.md").read_text()
        self.assertIn(TELEGRAM_URL, runbook)
        self.assertIn("First public announcement: posted on 2026-05-09", runbook)
        self.assertIn("Pin status: confirmed on 2026-05-10", runbook)
        self.assertIn("Recommended replacement pinned buy announcement prepared", runbook)
        self.assertIn("launch/telegram_pinned_buy_announcement.md", runbook)
        self.assertIn(MAINNET_ADDRESS, runbook)
        self.assertIn("Official GCA/USDT pool", runbook)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, runbook)
        self.assertIn("No third-party audit has been completed", runbook)
        self.assertIn("starter-depth only", runbook)
        self.assertIn("Do not submit the frozen X account", runbook)

    def test_data_platform_package_is_copyable_and_conservative(self):
        package = (ROOT / "launch" / "data_platform_package.md").read_text()
        values = json.loads((ROOT / "launch" / "data_platform_form_values.json").read_text())

        self.assertIn("DEX Screener", package)
        self.assertIn("GeckoTerminal", package)
        self.assertIn("CoinGecko", package)
        self.assertIn("CoinMarketCap", package)
        self.assertIn("https://gcagochina.com/", package)
        self.assertIn("https://gcagochina.com/status.html", package)
        self.assertIn("https://gcagochina.com/listing-kit.html", package)
        self.assertIn("https://gcagochina.com/project.json", package)
        self.assertIn("https://gcagochina.com/tokenlist.json", package)
        self.assertIn("https://gcagochina.com/buy.html", package)
        self.assertIn("https://gcagochina.com/members.html", package)
        self.assertIn("https://gcagochina.com/utility.html", package)
        self.assertIn("https://gcagochina.com/assets/gca-logo.svg", package)
        self.assertIn("https://gcagochina.com/whitepaper.html", package)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, package)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, package)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, package)
        self.assertIn(OFFICIAL_SWAP_URL, package)
        self.assertIn("GCA/USDT", package)
        self.assertIn("GeckoTerminal token info update: approved on 2026-05-11", package)
        self.assertIn("starter-depth only", package)
        self.assertIn("buy/sell functional swap tests were observed on 2026-05-10", package)
        self.assertIn("not as proof of organic demand or strong liquidity", package)
        self.assertIn("not completed", package)
        self.assertIn("quote requests were submitted on 2026-05-10 and then deferred by owner decision", package)
        self.assertIn("frozen", package)
        self.assertIn(TELEGRAM_URL, package)
        self.assertIn(MAINNET_ADDRESS, package)
        self.assertIn(RESERVE_WALLET, package)
        self.assertIn(RESERVE_TX, package)
        self.assertIn(SECOND_RESERVE_TX, package)

        self.assertEqual(values["packageStatus"], "prepared")
        self.assertEqual(values["chainId"], 8453)
        self.assertEqual(values["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(values["website"], "https://gcagochina.com/")
        self.assertEqual(values["statusPageUrl"], "https://gcagochina.com/status.html")
        self.assertEqual(values["listingKitUrl"], "https://gcagochina.com/listing-kit.html")
        self.assertEqual(values["projectJsonUrl"], "https://gcagochina.com/project.json")
        self.assertEqual(values["tokenListUrl"], "https://gcagochina.com/tokenlist.json")
        self.assertEqual(values["buyGuideUrl"], "https://gcagochina.com/buy.html")
        self.assertEqual(values["memberPreRegistrationUrl"], "https://gcagochina.com/members.html")
        self.assertEqual(values["utilityThesisUrl"], "https://gcagochina.com/utility.html")
        self.assertEqual(values["logoUrl"], "https://gcagochina.com/assets/gca-logo.svg")
        self.assertEqual(values["utilityPositioning"]["connectedProduct"], "Web3 Radar non-custodial quant risk toolkit")
        self.assertIn("ENTRY_READY signal review", values["utilityPositioning"]["suitableUtility"])
        self.assertIn("one-time 100 Web3 Radar utility credits ledger record for each registered user who verifies one wallet holding at least 10000 GCA", values["utilityPositioning"]["suitableUtility"])
        self.assertIn("GCA Member status in the Web3 Radar member ledger for each registered user who verifies one wallet holding at least 1000000 GCA", values["utilityPositioning"]["suitableUtility"])
        self.assertEqual(values["utilityPositioning"]["status"], "local-verified-access-backend-ready-public-claim-not-connected")
        self.assertEqual(values["utilityPositioning"]["plannedFirstCampaign"]["registeredUserLimit"], "one bonus per registered user")
        self.assertEqual(values["utilityPositioning"]["plannedFirstCampaign"]["minimumHolding"], "10000 GCA")
        self.assertEqual(values["utilityPositioning"]["plannedFirstCampaign"]["bonus"], "100 Web3 Radar utility credits")
        self.assertIn("risk-control bypass", values["utilityPositioning"]["plannedFirstCampaign"]["notCreditUse"])
        self.assertEqual(values["utilityPositioning"]["plannedMemberTier"]["tierName"], "GCA Member")
        self.assertEqual(values["utilityPositioning"]["plannedMemberTier"]["minimumHolding"], "1000000 GCA")
        self.assertIn("higher utility credit limits", values["utilityPositioning"]["plannedMemberTier"]["memberAccess"])
        self.assertIn("guaranteed lifetime access", values["utilityPositioning"]["plannedMemberTier"]["notMemberAccess"])
        self.assertIn("platform revenue distribution", values["utilityPositioning"]["notUtility"])
        self.assertEqual(values["liquidity"]["dex"], "Uniswap v4")
        self.assertEqual(values["liquidity"]["pair"], "GCA/USDT")
        self.assertEqual(values["liquidity"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(values["liquidity"]["quoteAssetAddress"], BASE_USDT_ADDRESS)
        self.assertEqual(values["liquidity"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(values["liquidity"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["liquidity"]["uniswapPoolUrl"], OFFICIAL_UNISWAP_POOL_URL)
        self.assertEqual(values["liquidity"]["officialSwapUrl"], OFFICIAL_SWAP_URL)
        self.assertEqual(values["platformReadiness"]["geckoTerminal"]["status"], "approved")
        self.assertEqual(values["platformReadiness"]["geckoTerminal"]["approvalDate"], "2026-05-11")
        self.assertIn("prepared-but-weak-readiness", values["platformReadiness"]["coinGecko"]["status"])
        self.assertIn("prepared-but-weak-readiness", values["platformReadiness"]["coinMarketCap"]["status"])
        self.assertEqual(values["socialLinks"][0]["platform"], "Telegram")
        self.assertEqual(values["socialLinks"][0]["url"], TELEGRAM_URL)
        self.assertIn("third-party audited", values["doNotClaim"])
        self.assertIn("deferred by owner decision", values["longDescription"])

    def test_geckoterminal_runbook_is_copyable_and_conservative(self):
        runbook = (ROOT / "launch" / "geckoterminal_update_runbook.md").read_text()
        values = json.loads((ROOT / "launch" / "geckoterminal_form_values.json").read_text())

        self.assertIn("approved on 2026-05-11", runbook)
        self.assertIn("Your request to update information for GCA has been approved", runbook)
        self.assertIn("Your form was submitted successfully", runbook)
        self.assertIn("Update Token Info", runbook)
        self.assertIn("launch/geckoterminal_form_values.json", runbook)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, runbook)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, runbook)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, runbook)
        self.assertIn(OFFICIAL_SWAP_URL, runbook)
        self.assertIn("GCA/USDT", runbook)
        self.assertIn("https://gcagochina.com/", runbook)
        self.assertIn("https://gcagochina.com/assets/gca-logo.svg", runbook)
        self.assertIn("https://gcagochina.com/whitepaper.html", runbook)
        self.assertIn("https://gcagochina.com/utility.html", runbook)
        self.assertIn("no completed third-party audit", runbook)
        self.assertIn("account is frozen", runbook)
        self.assertIn(TELEGRAM_URL, runbook)
        self.assertIn(MAINNET_ADDRESS, runbook)
        self.assertIn(RESERVE_WALLET, runbook)

        self.assertEqual(values["submissionStatus"], "approved")
        self.assertEqual(values["approvalDate"], "2026-05-11")
        self.assertEqual(values["reviewStatus"], "approved")
        self.assertEqual(values["platform"], "GeckoTerminal")
        self.assertEqual(values["chainId"], 8453)
        self.assertEqual(values["contractAddress"], MAINNET_ADDRESS)
        self.assertEqual(values["website"], "https://gcagochina.com/")
        self.assertEqual(values["logoUrl"], "https://gcagochina.com/assets/gca-logo.svg")
        self.assertEqual(values["logoPngUrl"], "https://gcagochina.com/assets/gca-logo.png")
        self.assertEqual(values["utilityThesisUrl"], "https://gcagochina.com/utility.html")
        self.assertEqual(values["officialEmail"], "GCAgochina@outlook.com")
        self.assertEqual(values["socialLinks"][0]["platform"], "Telegram")
        self.assertEqual(values["socialLinks"][0]["url"], TELEGRAM_URL)
        self.assertEqual(values["targetPoolUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["liquidity"]["dex"], "Uniswap v4")
        self.assertEqual(values["liquidity"]["pair"], "GCA/USDT")
        self.assertEqual(values["liquidity"]["poolAddress"], OFFICIAL_POOL_ADDRESS)
        self.assertEqual(values["liquidity"]["quoteAssetAddress"], BASE_USDT_ADDRESS)
        self.assertEqual(values["liquidity"]["dexScreenerUrl"], OFFICIAL_DEXSCREENER_URL)
        self.assertEqual(values["liquidity"]["geckoTerminalUrl"], OFFICIAL_GECKOTERMINAL_URL)
        self.assertEqual(values["liquidity"]["uniswapPoolUrl"], OFFICIAL_UNISWAP_POOL_URL)
        self.assertEqual(values["liquidity"]["officialSwapUrl"], OFFICIAL_SWAP_URL)
        self.assertEqual(values["supplyDisclosure"]["ownerReserveWallet"], RESERVE_WALLET)
        self.assertIn("completed OTP verification", values["officialEmailUse"])

    def test_internal_security_review_is_not_third_party_audit(self):
        report = (ROOT / "audit" / "gca_internal_security_review.md").read_text()
        scope = (ROOT / "launch" / "audit_scope.md").read_text()
        plan = (ROOT / "audit" / "third_party_audit_plan.md").read_text()
        request = (ROOT / "audit" / "third_party_audit_request.md").read_text()
        package = json.loads((ROOT / "audit" / "third_party_audit_package.json").read_text())
        self.assertIn("not a third-party audit", report)
        self.assertIn("No third-party audit has been completed", scope)
        self.assertIn("must not say", scope)
        self.assertIn("No mint function exists", report)
        self.assertIn("No owner or admin role exists", report)
        self.assertIn(MAINNET_ADDRESS, report)
        self.assertIn("Third-party audit is not complete", plan)
        self.assertIn("Quote request", request)
        self.assertEqual(package["status"], "audit-deferred-after-quote-requests")
        self.assertFalse(package["publicClaimState"]["thirdPartyAuditCompleted"])
        self.assertEqual(package["ownerDecision"]["status"], "deferred")
        self.assertIn("not to commission or pay", package["ownerDecision"]["summary"])
        self.assertIn("No immediate audit action", package["nextRequiredOwnerAction"])
        self.assertIn("Do not approve payment", package["nextRequiredOwnerAction"])
        self.assertEqual(
            [entry["name"] for entry in package["submissionLog"]],
            ["QuillAudits", "Hacken", "OpenZeppelin"],
        )
        self.assertTrue(all(entry["status"] == "submitted" for entry in package["submissionLog"]))
        self.assertIn("69ff764fef9d6e0aa30257f6", package["submissionLog"][0]["evidence"])
        self.assertIn("We've received your request", package["submissionLog"][1]["evidence"])
        self.assertIn("9b09cc7a-a53b-44b9-9763-98ac7e482434", package["submissionLog"][2]["evidence"])

    def test_swap_test_evidence_is_conservative(self):
        evidence = (ROOT / "launch" / "swap_test_evidence.md").read_text()
        self.assertIn("Functional Swap Test Evidence", evidence)
        self.assertIn("GCA/WETH", evidence)
        self.assertIn("0x79fc0b367adbd79118c664f5ee27eb6ff8cb69ff", evidence)
        self.assertIn(MAINNET_ADDRESS, evidence)
        self.assertIn(SWAP_TEST_BUY_TX, evidence)
        self.assertIn(SWAP_TEST_SELL_TX, evidence)
        self.assertIn("both buy and sell swaps", evidence)
        self.assertIn("not proof of organic demand", evidence)
        self.assertIn("Risk warning removed", evidence)
        self.assertIn("Deep liquidity", evidence)

    def test_blockaid_false_positive_report_records_submission(self):
        report = (ROOT / "launch" / "blockaid_false_positive_report.md").read_text()
        self.assertIn("Submitted on 2026-05-10", report)
        self.assertIn("https://report.blockaid.io/mistake", report)
        self.assertIn("https://report.blockaid.io/submittionSuccessfully", report)
        self.assertIn("Report Sent", report)
        self.assertIn("Thank you for reporting", report)
        self.assertIn(MAINNET_ADDRESS, report)
        self.assertIn(SWAP_TEST_BUY_TX, report)
        self.assertIn(SWAP_TEST_SELL_TX, report)
        self.assertIn("not a claim that the warning has been removed", report)

    def test_site_has_whitepaper_page(self):
        index = (ROOT / "site" / "index.html").read_text()
        whitepaper = (ROOT / "site" / "whitepaper.html").read_text()
        self.assertIn('href="whitepaper.html"', index)
        self.assertIn("GCA Whitepaper", whitepaper)
        self.assertIn("Version 0.5", whitepaper)
        self.assertIn("Go China Access", index)
        self.assertIn("Go China Access", whitepaper)
        self.assertIn("planned access to non-custodial quant risk tools", whitepaper)
        self.assertIn("ENTRY_READY signal review", whitepaper)
        self.assertIn("one wallet holding at least 10,000 GCA", whitepaper)
        self.assertIn("100 Web3 Radar utility credits", whitepaper)
        self.assertIn("one wallet holding at least 1,000,000 GCA", whitepaper)
        self.assertIn("GCA Member status", whitepaper)
        self.assertIn("higher utility credit limits", whitepaper)
        self.assertIn("not a token rebate", whitepaper)
        self.assertIn("Verified Utility Boundaries", whitepaper)
        self.assertIn("deployer-wallet ownership verification are complete", whitepaper)
        self.assertIn("Owner-held reserve", whitepaper)
        self.assertIn("600,000,000 GCA", whitepaper)
        self.assertIn(RESERVE_WALLET, whitepaper)
        self.assertIn(RESERVE_TX, whitepaper)
        self.assertIn(SECOND_RESERVE_TX, whitepaper)
        self.assertIn("not a lock, vesting contract, or Safe multisig", whitepaper)
        self.assertIn("mailto:GCAgochina@outlook.com", whitepaper)
        self.assertIn("https://gcagochina.com/buy.html", whitepaper)
        self.assertIn("https://gcagochina.com/utility.html", whitepaper)
        self.assertIn(TELEGRAM_URL, whitepaper)
        self.assertIn("starter liquidity only", whitepaper)
        self.assertIn("Third-party audit quote requests were submitted to QuillAudits, Hacken, and OpenZeppelin on 2026-05-10", whitepaper)
        self.assertIn("then deferred by owner decision", whitepaper)
        self.assertIn("GCA/USDT", whitepaper)
        self.assertIn(OFFICIAL_POOL_ADDRESS, whitepaper)
        self.assertIn(BASE_USDT_ADDRESS, whitepaper)
        self.assertIn(OFFICIAL_UNISWAP_POOL_URL, whitepaper)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, whitepaper)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, whitepaper)
        self.assertIn("GeckoTerminal token information was approved on 2026-05-11", whitepaper)
        self.assertNotIn(OLD_WETH_POOL_ADDRESS, whitepaper)
        self.assertIn(MAINNET_ADDRESS, whitepaper)

    def test_telegram_pinned_buy_announcement_is_safe_to_post(self):
        pin = (ROOT / "launch" / "telegram_pinned_buy_announcement.md").read_text()
        self.assertIn("Buy guide", pin)
        self.assertIn("https://gcagochina.com/buy.html", pin)
        self.assertIn("Uniswap swap", pin)
        self.assertIn(OFFICIAL_SWAP_URL, pin)
        self.assertIn(OFFICIAL_GECKOTERMINAL_URL, pin)
        self.assertIn(OFFICIAL_DEXSCREENER_URL, pin)
        self.assertIn("Official GCA/USDT pool", pin)
        self.assertIn(MAINNET_ADDRESS, pin)
        self.assertIn("GCA is on Base Mainnet only", pin)
        self.assertIn("No third-party audit has been completed", pin)
        self.assertIn("starter-depth only", pin)
        self.assertIn("If MetaMask or Uniswap shows a warning", pin)
        self.assertIn("Do not add price targets", pin)
        self.assertIn("Do not say the Blockaid / MetaMask warning has been removed", pin)


if __name__ == "__main__":
    unittest.main()
